### ISSUE TITLE
Icon images for all training classes

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#100]
![image](https://cloud.githubusercontent.com/assets/155492/12194495/c9842be4-b5f0-11e5-8eb1-38062639f2ba.png)

All icons for training classes should be recognizable in the same format and that should all be different (each class has it's own icon).

- [ ] Define some guidelines (e.g)
  * Size
  * Transparent background
  * Unmasked to the boarder
- [ ]  Create a file called `_styleguide.md` and put it in `/training/`

**Comment by lakruzz** [comment]
@illus0r I've assigned this task to @monaslarsen , but if you have any viewpoints or demands on the size or proportions of the images used, then please not them here

**Comment by lakruzz** [comment]
@monaslarsen start by estimating the task (cases aren't workable unless they have both priority and estimate) - It's the assignee who sets the estimate

**Comment by lakruzz** [comment]
@monaslarsen Are you working on this one ?

**Comment by monaslarsen** [comment]
Not yet, sorry, just finishing the urgent DOD presentation for potential sponsors. But this issue is my next top prio

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/12413170/35e8bada-be8d-11e5-899d-8caaef51cdcc.png)
ics for training

- [ ] The pic is 1130x1124 it's 2.5 MB. it's far too big to use as a icon - it simply takes too long to load.  Use pictures that are more lightweight
- [ ] The pictures should be more alike - some are icons, some are pictures, that's a mess - Describe a set of guidelines for what these pics should look like. (as suggested previously in this case

**Comment by lakruzz** [comment]
Moving this out of the MVP milestone - we're not done, bot in OK shape for MVP
