### ISSUE TITLE
Sort blog tag list alphabetically

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#114]
![image](https://cloud.githubusercontent.com/assets/797993/12272634/9442a3a4-b972-11e5-92ee-bc70f42b4344.png)
 subtask of #97

**Comment by illus0r** [comment]
Liquid sorting is case-sensitive, so the fastest way will be `js`. But for now I came up with simple making all tags have a capital first letter. These tags were altered.
```
automated
documentation
git
markdown
plugin
release
```
@lakruzz Should we implement case-insensitive sorting or we can just make a tag naming convention?

**Comment by lakruzz** [comment]
Lets agree on spelling all tags with an initial capital letter

**Comment by illus0r** [comment]
added a line about convention into readme
