### ISSUE TITLE
Fix bug with `margin-bottom` of h2

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#117]
You can see, "ONE DAY INTENSIVE HANDS-ON TRAINING" and "GET SOLID UNDERSTANDING" has different margins at the bottom. In fact they have `margin-bottom: 0;`. I need to fix it and check all the pages to find and fix regressions.

![image](https://cloud.githubusercontent.com/assets/797993/12294982/35ace5c8-ba0f-11e5-83bc-daf1ba82db4c.png)

**Comment by lakruzz** [comment]
It's the list - isn't it! - If it was a paragraph it would render differently.

**Comment by lakruzz** [comment]
Paragraphs has:

```
margin: 0.6em 0;
```
 (top AND bottom), `<UL>` doesn't,

It's not the `<h2>` that's the problem, it's the `<P>``

**Comment by lakruzz** [comment]
- [ ] Paragraphs should not have top margin, only bottom margin

**Comment by illus0r** [comment]
@lakruzz hold on :) We need this margin! If you at some point don't want to touch `h2`'s margins, we should add vertical margins to `ul`s.

All `h`s but not `h2` have bottom margins. I see no problems with unifying all `h`'s margins to prevent unexpected behavior in the future.

**Comment by lakruzz** [comment]
@illus0r: Right I agree on H's should be the same.

I meant the `<P>`...it shouldn't have any margin at the top - _only at the bottom_.

**Comment by lakruzz** [comment]
@illus0r did this end - or what happended

**Comment by illus0r** [comment]
@lakruzz I have not touched this yet.

**Comment by illus0r** [comment]
it's my fault to create issue and bring your attention to it. The issues' subject is a rubbish I should fix without any tasks.

**Comment by lakruzz** [comment]
@illus0r 

Do we agree on this then:

- [ ] All headers (at all levels) should have the same bottom margin
- [ ] Paragrap (`<p>`) should only have margins at the bottom - never at the top

**Comment by illus0r** [comment]
@lakruzz 
> All headers (at all levels) should have the same bottom margin

The margin should correspond to `h`'s height. So they can be equal in `em`s :grinning: 

> Paragrap `<p>` should only have margins at the bottom - never at the top

Margins collapse, so I didn't care about it.


![margins collapse](http://aryo.lecture.ub.ac.id/files/2013/02/margin-collapse.png)

**Comment by lakruzz** [comment]
> Margins collapse, so I didn't care about it.

hmmmm - but wasn't this the original problem???

Anyway if the original problem is solved then kill this issue.

**Comment by illus0r** [comment]
Good!
