### ISSUE TITLE
Call to action on every services page

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.com#119]
We need a call to action - link to contact form, newsletter subscription, conference link on every main page

**Comment by lakruzz** [comment]
@meekrosoft I get a sense that this on is in progress right - are you woking on it? Whats the status of this issue?

Is this still a size 0, did we spin off other issues from this?

**Comment by meekrosoft** [comment]
This is indeed getting broken down into smaller steps.  I am not sure how to link issues,  but this is the breakdown so far:

Issue 180 - Added a contact page
Issue 181 - Style the contact page

**Comment by meekrosoft** [comment]
I have pushed this work to a branch 
https://github.com/praqma/praqma.com/tree/call-to-action

Please look and give feedback on this.
<img width="1037" alt="screen shot 2016-02-05 at 15 35 17" src="https://cloud.githubusercontent.com/assets/145429/12849100/1ef34efa-cc1e-11e5-83b7-fd8057302ef3.png">
