### ISSUE TITLE
posts needs a polish

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#124]
In responsive mode (small screen) both the subscription box and the tags box are displayed before the actual post - that doesn't work well on a phone.

Also the addresses in the footer take up more space than that actual content - this is not optimal. find a solution that works.

It needs to look nice!

The blog avatar is shown at the bottom of the page in full width. The pic was designed to be an avatar - it was never supposed to go that large.

Either show it in a small formate, with text wrapping it in the top - or don't show it at all.

Am I the only one that thinks that this doesn't work?

**Comment by illus0r** [comment]
> Either show it in a small formate, with text wrapping it in the top - or don't show it at all.
yep, they look stupid. I'll remove them, I think, that's the best solution :)

**Comment by illus0r** [comment]
* [ ] Also the addresses in the footer take up more space than that actual content - this is not optimal. find a solution that works.

* [ ] The blog avatar is shown at the bottom of the page in full width. The pic was designed to be an avatar - it was never supposed to go that large. Either show it in a small formate, with text wrapping it in the top - or don't show it at all.

> In responsive mode (small screen) both the subscription box and the tags box are displayed before the actual post - that doesn't work well on a phone.

@lakruzz So you want to show these blocks on bottom?

**Comment by lakruzz** [comment]
No - I don't think I want the addresses at the bottom when we're in small screen mode - just hide it - it's a MVP - right :-)

**Comment by illus0r** [comment]
@lakruzz wow, good. I like your method :) I'll hide them soon.

**Comment by illus0r** [comment]
> In responsive mode (small screen) both the subscription box and the tags box are displayed before the actual post - that doesn't work well on a phone.

> Hmmm - it doesn’t anymore??!! - wierd! (#code-maturity)

Is that still relevant task?

**Comment by lakruzz** [comment]
@illus0r 

Yep it's relevant.
we have a problem with the subscription list box and the and the tags/search box.

In small screen mode the show before the content and the tag list is really loooong -  and it will only grow longer.

I doesn't work!

Do you have any suggestions on a solution your self? otherwise I suggest:

The subscription box, should go below content, in small screen mode.

The tag list should, either collapse to a comma separated list and go to the bottom too - or maybe even become invisible in small screens (could also become a collapsed menu I guess.

**Comment by lakruzz** [comment]
Hi @illus0r 

I made a small hack - maybe you wanna review/improve? 6b1b1a7

**Comment by lakruzz** [comment]
...Still need to make it look good on sm

**Comment by lakruzz** [comment]
We need to look at this, stilll, But I'm moving the issue out of the MVP milestone and into `workable` We'er in OK shape to go live

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/12456011/16f2530c-bfaf-11e5-98c4-09c3f6adc6ed.png)

Yep, I saw the post avatar has found his new place on the right sidebar. As you said it looks weird on mobile, it can be a good idea to move it to another place or just to hide on smartphones

>Do you have any suggestions on a solution your self? 

@lakruzz, I'll do some paper sketches then.

* [ ] make a new post layout
   * [ ] find a place for an avatar
   * [ ] solve the problem with a long tag list and newsletter subscription form

**Comment by illus0r** [comment]
@lakruzz which brunch to use for development? Not master, I guess :)

**Comment by illus0r** [comment]
and let me know if our cozy `git deliver` process had changed

**Comment by illus0r** [comment]
@lakruzz Suggestion for a **story index** and **post** design. All tweaks are for mobile only, they will not impact on desktop representation.

![image](https://cloud.githubusercontent.com/assets/797993/12461813/dc91ffec-bfcb-11e5-8b3d-f11217fbdde9.png) ![image](https://cloud.githubusercontent.com/assets/797993/12461856/0ceff72a-bfcc-11e5-80f2-5fa682e2c678.png)

Some tips:
* **search post by tag** — is a dropdown containing list of *tags*. 
* **google search** goes into the collapsed *main menu*, because it looks through all the site, not *stories* only.
* **subscribe for news** button or link opens a form in a popup window
* **avatar** is showed under the *post title*

**Comment by illus0r** [comment]
I'll decompose this task into smaller parts after your feedback

**Comment by illus0r** [comment]
What does `Type - Implementation` mean?

**Comment by lakruzz** [comment]
@illus0r I like your suggestion. @monaslarsen and @meekrosoft are you OK with this too - please give your feed-back on this case. (Which I've changed to a briefing)

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/12608788/611ddad0-c4de-11e5-838f-bedf7e9d2e30.png)

_Implementation_ means that it's related to developing features in the code
_Content_ means that it's related to writing content

**Comment by monaslarsen** [comment]
The suggestion in the left row looks good to me, it contains all the information the visitor could want, in a nice and simple design.

**Comment by illus0r** [comment]
@lakruzz I've broke down this into small peaces. Every of them got the same priority and milestone, as this issue.
