### ISSUE TITLE
Floating box annoying (matter of taste)

### ISSUE THREAD

**Issue by buep** [Praqma/praqma.com#141]
Personally I really hate such floating boxes following my page around. Distract me, and hides content I like to see.

If you scroll to the bottom of the page, you are even not sure if it is hiding the last piece of information (eg. phone number for our Stockholm office).

![screenshot from 2016-01-20 19 35 45](https://cloud.githubusercontent.com/assets/1579826/12459090/45c5961e-bfad-11e5-8875-a550d626fee5.png)

**Comment by buep** [comment]
![screenshot from 2016-01-20 19 38 17](https://cloud.githubusercontent.com/assets/1579826/12459113/604a86c0-bfad-11e5-8ab4-4fa8d9f033fe.png)

Do it hide something? I can't tell

**Comment by lakruzz** [comment]
Agree - we should think of  fix/solution - any suggestions? 

@illus0r Any ideas - you're the expert!

**Comment by lakruzz** [comment]
@illus0r Could we do something here I agree with @buep 

- Move it to the bottom right corner, så it doesn't interfere with content?
- Hide is unless it in the footer area?
- Something - you'r the UX expert :-)

**Comment by lakruzz** [comment]
@illus0r I set the priority to small - please poke me if you change it.

**Comment by illus0r** [comment]
@lakruzz Yep, I don't like overlapping stuff too.

We can just slightly shift it to right, but that's not good for our purpose, as we wanted to make phone noticeable.

![image](https://cloud.githubusercontent.com/assets/797993/12780929/1da20c28-ca82-11e5-9f9c-a9e8971e4c3e.png)


Can we show this info inside the header instead? There is a room for some extra information there. I can suggest a mockup, if you count this acceptable.

**Comment by lakruzz** [comment]
@illus0r Yes - better - give it a go!

**Comment by illus0r** [comment]
@lakruzz arr, I'd better be more precise asking a question: did you mean
> We can just slightly shift it to right

or
> show this info inside the header instead

?

**Comment by lakruzz** [comment]
- [x] slightly shift it to right

**Comment by illus0r** [comment]
We can show mail and phone line in #264

**Comment by lakruzz** [comment]
Continue this task in #264 

Closing this one as duplicate
