### ISSUE TITLE
Style facts on training pages

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#144]
The facts in the bottom of the training pages shoul dbe styled better:
![image](https://cloud.githubusercontent.com/assets/155492/12461191/d70dda6e-bfb7-11e5-8c61-ddefcd47a392.png)

**Comment by lakruzz** [comment]
I commented out the facts when I closed #182 (8954347)

We would like the fact back on, but not until they are styled and look good!

**Comment by illus0r** [comment]
Wide

![image](https://cloud.githubusercontent.com/assets/797993/14174454/009cf884-f74d-11e5-82eb-7cb010f11967.png)

Mobile

![image](https://cloud.githubusercontent.com/assets/797993/14174405/c218ad1a-f74c-11e5-8cd5-49262cb9cc26.png)

**Comment by illus0r** [comment]
Made padding fix after first deliver
