### ISSUE TITLE
Praqma gijeli knowledgebase presentation

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#145]
This story needs rework

- [ ] Tell it like a story
- [ ] Find a suitable avatar 

https://github.com/Praqma/praqma.github.io/blob/master/_posts/2015-05-08-praqma-gijeli-knowledgebase-presentation.md

**Comment by buep** [comment]
No clue how this markdown file ended on our website, it originates from our pinside repository. It is never supposed to be a blog.

**Comment by lakruzz** [comment]
It's already removed
