### ISSUE TITLE
Stories: show newest stories by default

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/praqma.com#148]
At the first look stories looks outdated and only after some time I figured that I have to select newest on the right to see the recent stories.
Such way of sorting is a bit counterintuitive, at least for me.
The issue is subjective so see it more as a suggestion for improvement rather than a real issue.

**Comment by monaslarsen** [comment]
I am also open to discussing this, but as you see, the featured stories are still in chronological order - they are just selected based on their more general informative level and human touch, over the more tech oriented content.
As we ARE a tech shop, I won't object to changing to "newest" as default setting..

**Comment by lakruzz** [comment]
Both "Newest" and "Featured" are useful -it's really a matter of what should be default?

It can be set in the `_config.yml` (lines 9-10)

https://github.com/Praqma/praqma.github.io/blob/master/_config.yml

Lets leave it with Featured for a while and revisit this issue later.

**Comment by les-praqma** [comment]
When I see a story/news list on a web page, where the top entry is from 2014 I conclude that nothing is happening in that company - or that their webpage is not being updated. I don't search for new entries first. So if we dont have anything newer than 2014 at top under Features, I think we should immediately change to Newest

**Comment by lakruzz** [comment]
Duplicate #185
