### ISSUE TITLE
Training page layout is confusing

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.com#150]
What do I click?  It is hard to intuit that clicking the logos is how to find more information.  I also think the 3 column layout is not a good choice.  YMMV

<img width="1105" alt="screen shot 2016-01-21 at 10 36 03" src="https://cloud.githubusercontent.com/assets/145429/12476627/f8b6a380-c02a-11e5-950f-a59b8965b52d.png">

**Comment by monaslarsen** [comment]
Hey @meekrosoft @adamhenriques @Andrey9kin 

I have talked to Lars about changing the layout of this collection, to the design used for the "Services" collection.
Any objections or input before I ask Ivan to do it?

I

**Comment by meekrosoft** [comment]
No objections on my side

**Comment by monaslarsen** [comment]
Hey @illus0r .
Please change the layout of this collection, to the design used for the "Services" collection

**Comment by lakruzz** [comment]
This case needs an estimate: @illus0r ?

**Comment by illus0r** [comment]
@lakruzz @monaslarsen mm, good! I like idea of unification. It looks like 2-hour problem, is that `small` or `middle`?

**Comment by illus0r** [comment]
@lakruzz @monaslarsen 
> I also think the 3 column layout is not a good choice.

Switching to 2 col will take extra time. I'll fix my estimation

**Comment by illus0r** [comment]
@monaslarsen @lakruzz 
I've started. I'll eliminate the left menu on both **training-index** and **training-pages**. The mockup will be remade after services, i'll copy it's design precisely.

**Comment by illus0r** [comment]
Haven't pushed yet.
New alignment of **images** and **titles** is not ok. I can fix styles unless you want to fix titles.

![image](https://cloud.githubusercontent.com/assets/797993/13222602/b8b591b2-d991-11e5-9574-c96a51bc56eb.png)
