### ISSUE TITLE
Employees page need to be updated

### ISSUE THREAD

**Issue by KamranAzeem** [Praqma/praqma.com#152]
http://www.praqma.com/stories/employees/
I heard that Waqar is no longer with Praqma, but the page says he is there and working on something! 

Thanks!

**Comment by KamranAzeem** [comment]
Also the site gives a feel that I am watching "Sin City" Only the blood has (bright yellow) color, rest is black and white. :)

**Comment by monaslarsen** [comment]
Thanks @KamranAzeem. I will change this issue to "Write a story about new employees since autumn 2014"

**Comment by monaslarsen** [comment]
Write a new story to succeed the one from autumn 2014

**Comment by bicschneider** [comment]
@monaslarsen 
I would prefer that all employees are listed + add a "employed since: 20YY.MM" + a Linked-In /about.me link..

**Comment by monaslarsen** [comment]
Thanks, I'll look into that @bicschneider
