### ISSUE TITLE
Change slogan font to "Loved by the King"

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.com#155]

**Comment by lakruzz** [comment]
@monaslarsen you need to elaborate on this before it becomes workable.

We need a description, Why "Jinky" is it a webfont? Where to find it? etc

**Comment by lakruzz** [comment]
@monaslarsen this case needs a description/justification - The font's that are easy to use on web are the ones available at https://www.google.com/fonts 

What's wrong with the one we have?

**Comment by lakruzz** [comment]
Jinky:
![image](https://cloud.githubusercontent.com/assets/155492/12979662/e88b08e8-d0d8-11e5-98a4-45e1f695679b.png)

**Comment by lakruzz** [comment]
[Nothing You Could Do](https://www.google.com/fonts/specimen/Nothing+You+Could+Do):

![image](https://cloud.githubusercontent.com/assets/155492/12979836/ce5d1758-d0d9-11e5-8522-6f9e21abe05c.png)

**Comment by monaslarsen** [comment]
@lakruzz 
I go for friendly gut feeling, not too slanted, easy to read:

Handlee https://www.google.com/fonts/specimen/Handlee

**Comment by illus0r** [comment]
@monaslarsen @lakruzz may be we'd use some markerboard handwriting?

**Comment by monaslarsen** [comment]
I am absolutely convinced by the Google font "Loved by the king". I have used it on a few occasions now, so @lakruzz, can we let @illus0r go ahead and make the change?

https://www.google.com/fonts/specimen/Loved+by+the+King
