### ISSUE TITLE
About us mobile bug

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#161]
<img src="https://cloud.githubusercontent.com/assets/797993/12549106/00cc8bf4-c36c-11e5-8b68-dcebf1020991.png" width="300">

**Comment by lakruzz** [comment]
Right - feel free to come up with a solution -Go!

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/12786477/5cf9f9f6-caa2-11e5-96e6-c0f543be8832.png)
Good now! Tested in chrome
