### ISSUE TITLE
Use `JEKYLL_ENV` to disable google analytics for development

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#163]
It's really easy
```
{% if jekyll.environment == "production" %}
      <script>
        // JavaScript snippet supplied by Google goes here...
      </script>
    {% endif %}
```

**Comment by lakruzz** [comment]
Fine - then we need a `_dev_config.yml` that sets the `jekyll.production` to crab and then locally run

```
jekyll serve --watch --config _config.yml._dev_config.yml
```

It's one more thing to remember though, and there will be a lot of people contribution - I guess a lot will still just run plain

```
jekyll serve --watch
```

Could we make it a system environment variable? Utilizing some of these ideas:

https://gist.github.com/nicolashery/5756478

**Comment by illus0r** [comment]
> Fine - then we need a _dev_config.yml that sets the jekyll.production

nope.
Just tested on [my project](https://github.com/illus0r/dianov.org/commit/30ad72c314691b899a7c5cf1f02553c76ec27690#diff-7d022dd158b090bf0d55b0cef3d14865). Just 
```
{% if jekyll.environment == "production" %}
I'm on production
{% endif %}
```
does the job. I see it on gh only, no `--config` mess at all

**Comment by lakruzz** [comment]
Nice

- [ ] Implement!
- [ ] Document usage of the environment variable in the README.md
- [ ] Maybe even add a convenient `serve` script that sets the variable (lime @JKrag did [here](https://github.com/Praqma/code-maturity/blob/gh-pages/serve))

**Comment by illus0r** [comment]
@lakruzz Good! No need to add `JEKYLL_ENV ` somewhere, adding condition is enough. So no need to document it.

**Comment by lakruzz** [comment]
Hmmm - how does `jekyll.evnironment`get a value assigned?

**Comment by illus0r** [comment]
DEV
![image](https://cloud.githubusercontent.com/assets/797993/12677835/b5c1a43e-c6ac-11e5-8440-143dbecc7f24.png)

PROD
![image](https://cloud.githubusercontent.com/assets/797993/12677899/09e3d7e4-c6ad-11e5-9a5b-49c55826c864.png)

**Comment by lakruzz** [comment]
Hmmm - I'm still puzzled @illus0r - enlighten me:

How does that snippet of code know if its' running in production or not? How is `jekyll.evnironment` assigned a value?

**Comment by illus0r** [comment]
@lakruzz 
I'm not sure about details, but Parker Moore (https://github.com/jekyll/jekyll owner) wrote this last comment on https://github.com/jekyll/jekyll/issues/1219

I can dig into the subject and elaborate, if you want

**Comment by lakruzz** [comment]
Right - I see it.
It's still mysterious, that there is som much debate about wether it works or not, but your test seems to verify that we're OK.

Lets implement.

**Comment by illus0r** [comment]
@lakruzz I've done this in cd1d8d4
I had a look at Google Analytics, all correct: I see fresh visits and don't see localhost pages.

And, as I just read in [Google Help](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id), we can skip jekyll condition at all. We have already restricted traffic by `praqma.com` in `praqma.com/javascripts/googleanalytics.js`:

```
ga('create', 'UA-33979353-1', 'www.praqma.com');
```

Localhost traffic will not be sent to GA.

**Comment by lakruzz** [comment]
...Cool - we will skip this then, this seems to implemented the praqmatic way already :-)
