### ISSUE TITLE
listing of stories should be a function

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#166]
We list the stories on the tag pages using the page `/pages/stories.html`

I would like this to become a function that can be used else where too.

E.g. take that code snippet to /_include/func/list-stories.html`

And then use it like this:

```
{% include /func/list-stories.html tag=jobs  max=5 avatar-alignment=left sortby=weight %}
```

Where:

* `tag`  is the tag to display
* `max` is the maximum number of posts to display (`0` or `null` (unset) means `all`)
* `avatar-alignment` is one of `left | flex` Flex shall mean that the avatar is left on the first post, right on the following, then left again - like the listing of speaker portraits on [this page](http://www.code-conf.com/cph15/program/)
* `sortby`is one of `newest | weight`

**Comment by lakruzz** [comment]
The user story for this function is:

* On the  `/about/jobs/` I'd like to insert the job listings instead af just pointing to them
* On then `/about/customers/` I'd like to insert a list the customer cases in the bottom
* On the front page underneath the images, I'd like to insert a listing of the featured stories, with flexing alignment of the  avatars.

Turing the semantic code in `/pages/stories.html` into a reusable function as described, would accommodate all that.

**Comment by lakruzz** [comment]
The implementation of the parameters are prioritized like this:

*  `tag` (required)
* `avatar-alignment` (default or unset = `left`
* `sortby` (default or unset is `newest`
* `max` (default or unset means `all``

**Comment by lakruzz** [comment]
@illus0r, @meekrosoft  - feel free to comment.

**Comment by lakruzz** [comment]
@illus0r you set the estimate for this one

**Comment by illus0r** [comment]
> `tag` is the tag to display

So one *stories page* per *tag*? Do you intend to add *story pages* by hand?

**Comment by lakruzz** [comment]
I don't understand you question.

for `tag=jobs` I'd like something like:
![image](https://cloud.githubusercontent.com/assets/155492/12623514/c9f28884-c52a-11e5-8a8a-1acec27eb181.png)

**Comment by illus0r** [comment]
@lakruzz 
In previous version of `stories` we had several tag pages, created manually. So when we used a new *label* in frontmatter of a post, we had to create a new `tag-page` file for that *label*. But we changed to `js` approach to avoid this manual routine.

Now we put all the posts to a single story page, but show only matching the current tag.

If we'll change to `{% include /func/list-stories.html tag=jobs  max=5 avatar-alignment=left sortby=weight %}` approach, each page will be possible to show content for a single tag. So we'll have to make a separate page for each tag, like we did before.

I want to understand, what for we need this trick. Anyway, it's possible, but I want to understand you purpose.

**Comment by lakruzz** [comment]
I only need it on a few selected tags

- Jobs (on about/jobs)
- Featured (on the front page)
- Customer case (on about/customers

**Comment by illus0r** [comment]
That's doable! I'll leave the same filtering mechanism for stories, it will use the blog include as 


I'll set defaults:
```
tag=*
max=∞
avatar-alignment=left
sortby=date
```
So we'll use 

`{% include /func/list-stories.html %}` for **stories**, 

`{% include /func/list-stories.html tag=featured max=3 sortby=weight %}` for the **frontpage** and 

`{% include /func/list-stories.html tag=jobs %}` for **jobs**

**Comment by illus0r** [comment]
- [x] Move code to include
- [ ] Rearrange styles to make them work not on **stories** pages only.
- Implement
 - [x] weight and date sorting
 - [x] tag filtering
 - [ ] limiting output
 - [ ] avatar alignment

**Comment by illus0r** [comment]
@lakruzz I've broke this task down into #172, #173, #174
Can we close this?
