### ISSUE TITLE
Enable comments on posts

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#169]
A few abilities I'd like to see in context of comments on blogs:

- [ ] It would be required to have som kind of notification when a comment is added to a blogpost
- [ ] The comments should behave well in responsive design
- [ ] Comments should be enabled by lay-out, but the individual page should be able to override is `true|false` in the front matter

**Comment by illus0r** [comment]
@lakruzz 
Will https://disqus.com/ or https://www.spot.im/ suit our needs?

**Comment by lakruzz** [comment]
@illus0r 

Hmmm - don't know really  - So far we have been using google plus comments

Example (implementation):
https://github.com/josra/josra.github.io/blob/master/_includes/google-comments.html

Example (utilization):
http://www.josra.org/blog/An-automated-git-branching-strategy.html

Personally I like this better both Spot and Discuss are Twitter/facebook centric - not sure I like that. I expect that most (all?)  people have a Google account!

View points?

**Comment by lakruzz** [comment]
@mike

Simply add

```
comments: true
```

In the frontmatter
