### ISSUE TITLE
Mobile: *subscribe for news* button

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#177]
Subtask of #124 

- [ ] should be shown instead of current block
- [ ] should open a form in a popup window

![image](https://cloud.githubusercontent.com/assets/797993/12747622/21a523f4-c9b6-11e5-95a0-62f1474d62e0.png)

**Comment by illus0r** [comment]
sorry, closed instead of #176

**Comment by illus0r** [comment]
@lakruzz Looks not ugly on mobile, we can skip this task at all. The button instead of open form can spoil conversion after all.

Can we close?

![image](https://cloud.githubusercontent.com/assets/797993/14247226/65ecf786-fa75-11e5-8e12-b739aff10db3.png)

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/14247267/bb7a4532-fa75-11e5-947a-26bfb9b498d1.png) corners are rounded on desktop chrome only, they are straight on my android

**Comment by lakruzz** [comment]
Fine let's wrap it up
