### ISSUE TITLE
Contact form style

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.com#181]
We need some nice styling for the contact form on praqma.com/contact

**Comment by lakruzz** [comment]
@illus0r You are our UX expert - can you attend to this, Give us your best, make it shine!

Start by adding an estimate, so we can mark it workable

**Comment by meekrosoft** [comment]
It is pushed to the call-to-action branch

**Comment by illus0r** [comment]
- [ ] style the submit btn
- [ ] make responsive

@meekrosoft how should I push, BTW? Without `deliver`, I guess?
