### ISSUE TITLE
Registration for training

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/praqma.com#182]
We need links from all training classes pointing to eventbrite so that people can sign up - or embed widget for eventbrite payment to keep people on out site.

**Comment by lakruzz** [comment]
Currently the training pages  in `/_training` has the following front matter:

Sample from Docker intro

```
---
title:    Introduction to Docker
duration: Two days
level:    Software developers, Architects, DevOps and Continuous Delivery practitioners
caption:  Use this training to jump-start your Docker journey
type:     This hands-on course will introduce you to the Docker platform and take you through installing, integrating and running it in your working environment.
location: Copenhagen, Stockholm, Oslo - or on-site
avatar:   /images/training/docker-intro.1x1.png
---
```

We should add an extra entry there like this:

```
---
...
schedule:
  -
    location: Oslo
    date:12-02-22
    registration:https://docker-intro-oslo.eventbrite.co.uk
  -
    location: Stockholm
    date:22-02-22
    registration:https://docker-intro-sthlm.eventbrite.co.uk
---
```

The semantics should then be:

__IF__ there is one or more scheduled events
__THEN__ Display them on the page, as a call to action.

I'll let our UX expert @illus0r come up with an implementation of what that would look like.

**Comment by lakruzz** [comment]
@adamhenriques 

For all the files listed in https://github.com/Praqma/praqma.com/tree/gh-pages/_training, can you provide the relevant info for each file:

```
location:
date:
registration:
```

So that @illus0r has something to work with...

**Comment by lakruzz** [comment]
@illus0r can you put an estimate on this one?

**Comment by adamhenriques** [comment]
@lakruzz 

**Introduction to Docker**

Oslo Feb 15&16, 9:00 -17:00
https://docker-intro-oslo.eventbrite.co.uk

Stockholm Feb 22&23rd, 9:00 -17:00
https://docker-intro-sthlm.eventbrite.co.uk

Copenhagen March 7&8, 9:00 - 17:00
http://docker-intro-cph.eventbrite.co.uk

Aarhus March 14&15, 9:00 - 17:00
http://docker-intro-aarhus.eventbrite.co

**Comment by adamhenriques** [comment]
@lakruzz 

**Docker Administration & Operations**

Stockholm March 29&30 9:00-17:00
https://docker-ops-and-admin-sthlm.eventbrite.co.uk

Copenhagen, April 19&20 9:00-17:00
http://docker-ops-and-admin-cph.eventbrite.co.uk

**Comment by illus0r** [comment]
@lakruzz 
As I understood we need to provide a way to sign up for training courses from _training pages_ (like http://www.praqma.com/training/git-mastering/)

Currently signing up is possible on outer websites so we want to provide a noticeable link to these websites.

Am I correct? If so, I'll make a design and implement it

**Comment by lakruzz** [comment]
@adamhenriques @illus0r 

Or even better: Have it all happen on our own site:
Example: http://www.code-conf.com/day-of-containers-sthlm16/

**Comment by illus0r** [comment]
@lakruzz the best option! Let's cut out unnecessary links! :scissors:

**Comment by adamhenriques** [comment]
I agree - that would be the best solution!

[image: ____________________________________________________________]
Adam Henriques
CMO
ah@praqma.net
+45 28 12 90 94 <+45%2028%2012%2090%2094>
Skype: adamhenriques
Praqma
www.praqma.com
CPH, OSL, STHLM
+45 36 PRAQMA <+4536772762>

**Comment by illus0r** [comment]
@lakruzz will we stick with https://www.eventbrite.com/?

**Comment by lakruzz** [comment]
embedded -as on : http://www.code-conf.com/day-of-containers-sthlm16/

**Comment by illus0r** [comment]
Good!

**Comment by lakruzz** [comment]
@adamhenriques I closed this with a quick fix

have a look at http://www.praqma.com/training/docker-intro/

The scheduel is delivered as yaml in the front matter of the file:
https://raw.githubusercontent.com/Praqma/praqma.com/gh-pages/_training/docker-intro.md

```
schedule:
  - 
    location:     Oslo
    date:         2016-02-15
    registration: https://docker-intro-oslo.eventbrite.co.uk
    eventbriteid: 19528021839
  -
    location:     Stockholm
    date:         2016-02-22
    registration: https://docker-intro-sthlm.eventbrite.co.uk
    eventbriteid: 19992428893
  -
    location:     Aarhus
    date:         2016-03-14
    registration: https://docker-intro-aarhus.eventbrite.co.uk
    eventbriteid: 19994494070
```

**Comment by lakruzz** [comment]
Actually I'm not using the url, so this is sufficient:

```
schedule:
  -
    location:     Oslo
    date:         2016-02-15
    eventbriteid: 19528021839
  -
    location:     Stockholm
    date:         2016-02-22
    eventbriteid: 19992428893
  -
    location:     Aarhus
    date:         2016-03-14
    eventbriteid: 19994494070

```

**Comment by adamhenriques** [comment]
Great thanks

[image: ____________________________________________________________]
Adam Henriques
Sales & Marketing
ah@praqma.net
+45 28 12 90 94 <+45%2028%2012%2090%2094>
Skype: adamhenriques
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com?src=mailbanner16>

**Comment by adamhenriques** [comment]
@lakruzz 

seems that we are missing this on the page - vill you add it;

Copenhagen March 7&8, 9:00 - 17:00
http://docker-intro-cph.eventbrite.co.uk

**Comment by lakruzz** [comment]
@adamhenriques is this done yet?

**Comment by adamhenriques** [comment]
@lakruzz Yes
