### ISSUE TITLE
Create a "Free Consultation" page

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.com#183]
We need a goal for the website.  That goal should be scheduling a meeting with us.

**Comment by meekrosoft** [comment]
An example:
https://www.inboundgroup.com/no/1time

**Comment by lakruzz** [comment]
Hi @meekrosoft 

I'm curious, how did you select the "prio 2..." label? it seems like - however you did it - it created a new label type with a duplicated name, instead of using the one that was already there?

**Comment by meekrosoft** [comment]
I have no idea! :-D  I guess I selected it from the dropdown on waffle...

**Comment by lakruzz** [comment]
:+1:


[image: ____________________________________________________________]
Lars Kruse M.Sc.
Partner & Co-founder
lak@praqma.net
+45 20 87 25 30 <+45%2020%2087%2025%2030>
Skype: lakruzz
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.josra.org/blog/An-automated-git-branching-strategy.html?src=mailbanner>
