### ISSUE TITLE
Show newest instead of featured stories as default

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#185]

**Comment by lakruzz** [comment]
@illus0r 

What's the purpose of the setting
```
stories:
 -  default-tag: Featured
```


I would like http://www.praqma.com/stories/#Newest to be the default over http://www.praqma.com/stories/#Featured - and I expected that the change made in 593556d  would have achieved that.

**Comment by illus0r** [comment]
Good, I'll try to do it. I'll have to move some `js` logic into `html` so to be able to set `js` variables by `liquid`
