### ISSUE TITLE
Entrypage from cellphone on Stories

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/praqma.com#186]
Entring "Stories" the pages responsiveness scales so that the first thing shown is Sign Up for Newsletter and "Search" directory - could we change this so that newest stories come in the top?

![image](https://cloud.githubusercontent.com/assets/8004259/12865112/d4314a8a-cca3-11e5-88c2-d3134020b979.png)

**Comment by lakruzz** [comment]
This is related to #185 in terms of selecting newest over featured as default, but the issue that is starts on the top f the page rather than scrolls down to the actual stories still needs to be fixed - regardless what tag is default.

**Comment by lakruzz** [comment]
@illus0r I assigned it to you with a needs grooming label, I need an estimate

**Comment by illus0r** [comment]
@lakruzz 
As I understood @adamhenriques wants to push main content to top, since it's more important than **newsletter form** and **tag filter**. If I understood correctly, it duplicates #175 (collapse tag list) and #177 (move newsletter form into modal window)

**Comment by illus0r** [comment]
@lakruzz my problem vision is slighly differ from yours, I can be wrong. What's your opinion? I need to know it to set estimation

**Comment by lakruzz** [comment]
@adamhenriques will you review #175 and #177 and evaluate if they cover your scenario - is this case essentially a duplicate?

**Comment by adamhenriques** [comment]
@illus0r Yes, it would be nice to haven main content to the top instead of tag filter - so its a dublicate. Ill resolve it.

Thanks

**Comment by illus0r** [comment]
Thanks for feedback, @adamhenriques!
