### ISSUE TITLE
Proofreading on customercases etc

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/praqma.com#191]
Some of the case stories need proof reading fx. http://www.praqma.com/stories/grundfos-case/ has "#" some places in the text.

**Comment by monaslarsen** [comment]
Isn't this a styling issue @illus0r ? Shouldn't hashtags create headlines?

**Comment by illus0r** [comment]
@monaslarsen @adamhenriques 
Hmm, [gijeli article](https://raw.githubusercontent.com/Praqma/praqma.com/gh-pages/_posts/2014-06-18-GiJeLi-tool-stack-howto.md) works well though.
Try adding space after `##` and extra newline under

**Comment by lakruzz** [comment]
We need to break this into smaller workable items

**Comment by lakruzz** [comment]
Create secific issues for the tasks that needs to be done - then close this one,
