### ISSUE TITLE
"Request free cunsultation" box covers logo in mobile version

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/praqma.com#193]
![image](https://cloud.githubusercontent.com/assets/8004259/13040540/9006ebe2-d3ad-11e5-9562-ac5760debb27.png)
The box for free consultation covers logo and menu in mobile version

**Comment by illus0r** [comment]
@adamhenriques 
@lakruzz 
We can enlarge `body`'s top margin and make overlapping link smaller (to avoid competing with header).

**Comment by illus0r** [comment]
or just hide

**Comment by illus0r** [comment]
Or to find out a completely different mockup :)

**Comment by lakruzz** [comment]
Just adding to top margin isn't a good solution - then rather hide it, or get a UX expert to come up with something clever :+1:

**Comment by illus0r** [comment]
@lakruzz Ok, I'll spin off a task for hiding (quick fix) and this task if for finding out a better way!

**Comment by illus0r** [comment]
Oops, i closed it by mistake instead of #196

**Comment by illus0r** [comment]
- [ ] make low-fidelity mockups
- [ ] implement

**Comment by illus0r** [comment]
closed with #274
