### ISSUE TITLE
Style contact form for consultation page

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.com#198]
I would like some styling to be done for the contact page and layout on praqma.com/pages/1hour.md

<img width="1015" alt="screen shot 2016-02-18 at 14 57 44" src="https://cloud.githubusercontent.com/assets/145429/13145320/332433f8-d650-11e5-9b0c-9e1bd4e79578.png">

**Comment by lakruzz** [comment]
@illus0r - do your thing - make it look good

**Comment by illus0r** [comment]
Sure! I keep working by priorities, hope to reach it out :)

**Comment by illus0r** [comment]
@lakruzz 
I gave a chance to fix it to freelancer. Let me know, if you want to fix it asap, I have a first version `good enough (c)` from him
And can we burn out second name and second contact? So as the form boil down into this fielsd:

* Name
* Phone of email
* Message

**Comment by lakruzz** [comment]
@illus0r 

Yep!
Take it away :-)

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/14205295/bd8afea8-f812-11e5-9a44-af3b48786235.png)


![image](https://cloud.githubusercontent.com/assets/797993/14205307/d871f12c-f812-11e5-9006-89812fe039a0.png)

**Comment by lakruzz** [comment]
It can not say "Let's chat" since it's indicating that at chat is being setup, while in fact it's a request to be contacted:


> YES, I'D LIKE TO HAVE A CHAT

becomes:

"YES, I'D LIKE SOME FREE CONSULTATION"

and then button caption becomes "Contact me"

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/14246922/fa5ecad2-fa72-11e5-9407-227368ded3e1.png)

**Comment by lakruzz** [comment]
> and then button caption becomes "Contact me"

...I still think that  "Let's chat" sends the wrong impression - that we're starting an online chat!

"Contact me" is better describing what is actaully going to happen

**Comment by illus0r** [comment]
@lakruzz Arrr, sorry, I forgot about that :grin:

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/14247545/71c9034a-fa77-11e5-9050-c5ee60097204.png)

**Comment by lakruzz** [comment]
:+1:
