### ISSUE TITLE
News feed on frontpage - how to order

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/praqma.com#201]
How do we order news so that latest or ft. will apear first? Right now we have old news coming first.
![skaermbillede 2016-02-23 kl 08 31 20](https://cloud.githubusercontent.com/assets/8004259/13244616/e2b43cea-da07-11e5-90ee-165f7e874ce0.png)

**Comment by lakruzz** [comment]
@adamhenriques 
All the stories that are tagged `Featured` are listed on the front page.
If they also have a `nav-weight` then they are sorted by that (lowest values on top` - if not then they are sorted by date.

```
---
title:      Top Jenkins plugins
caption:    Pragmatic plugins for pupils and pros alike.
tags:       [Featured, Jenkins]
avatar:     /images/stories/cool-jenkins.png
redirect_from: /stories/jenkins-favs/
nav-weight: 40
---
```

**Comment by adamhenriques** [comment]
Does that meen that we neem to tagg all blogpost and sort them, so that we makje sure that news on frontpage are relevant/current?

**Comment by illus0r** [comment]
> If they also have a `nav-weight` then they are sorted by that (lowest values on top) - if not then they are sorted by date.

If include has `sort='FWT'` parameter, they will be sorter by `FWT`. Otherwise, by `date`.

**Comment by illus0r** [comment]
You can find all available params in https://github.com/Praqma/praqma.com/blob/gh-pages/_includes/posts.html

**Comment by lakruzz** [comment]
Not a feature request, it already exiest
