### ISSUE TITLE
Google search show text about specflow rather than what we are...

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.com#212]
This is what google thinks Praqma is:
<img width="545" alt="screen shot 2016-02-28 at 22 34 20" src="https://cloud.githubusercontent.com/assets/145429/13382064/a2e2e0c2-de6b-11e5-87df-bb10547df1bb.png">

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/15228213/582eee4a-188b-11e6-80e5-44b4f5a27abf.png)

Google is indexing the first text it finds on the page, so this is just "different" not better - we need to control what ends up here!
