### ISSUE TITLE
Blogpost "GiJeLi setup" refers to a late website

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.com#213]
Lars, your example code refers to the dead site http://www.codeu.eu/

I have updated the link to code-conf.com in case interested readers should click the link, but either the example should probably be updated or the reference to the website should maybe be removed.

Makes sense?

<img width="759" alt="screen shot 2016-03-01 at 14 15 25" src="https://cloud.githubusercontent.com/assets/13627068/13428036/1efeff9a-dfb8-11e5-9cc2-3d204258aba4.png">

**Comment by lakruzz** [comment]
closed in  f206fe0
