### ISSUE TITLE
Make quoted text slightly smalller

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.com#214]
Currently quotes created by starting a sentence with ' > ' is too large. 

<img width="643" alt="screen shot 2016-03-01 at 14 46 08" src="https://cloud.githubusercontent.com/assets/13627068/13428701/6e51236c-dfbc-11e5-8809-6db12c6037a2.png">

**Comment by monaslarsen** [comment]
Is it possible to create two optional sizes, for use depending on the length of the quotation?

**Comment by illus0r** [comment]
@monaslarsen 
Good idea to separate usage depending on length. If the quote is short, it should be huge. Try to add `{: .small}` to a line next to quote. It can be enough.

**Comment by monaslarsen** [comment]
Thanks, I will try that!

**Comment by illus0r** [comment]
OK, @monaslarsen , be back if it doesn't work

**Comment by monaslarsen** [comment]
Thanks @illus0r, it worked - it makes it very small, but it's a good option for very long quotes!
