### ISSUE TITLE
Specshell shouldn't be on the front page - replace with link to customer cases

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#220]
We need something that's about Praqma 
![image](https://cloud.githubusercontent.com/assets/155492/13564537/beb5e3be-e44a-11e5-9544-809375c6ac5b.png)

**Comment by meekrosoft** [comment]
I would like a page "What our customers say".

**Comment by meekrosoft** [comment]
Link to this instead:
http://www.praqma.com/stories/#Customer%20case

Picture:
Mona can find something in her curated collection
