### ISSUE TITLE
Day of containers shouldn't be on the front

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#221]
![image](https://cloud.githubusercontent.com/assets/155492/13564550/d4524ff0-e44a-11e5-8ad9-8633a04dfe5c.png)

**Comment by lakruzz** [comment]
Make it about the praqmatic flow:
http://www.praqma.com/stories/a-pragmatic-workflow/

**Comment by lakruzz** [comment]
@monaslarsen This is becoming URGENT! we're still announcing an non existing conference on our front page!

Could you swap it - maybe use the pic form the very fine :+1:  [newsletter](http://us5.campaign-archive1.com/?u=4cd7193551aaee65c6da509a1&id=636ee24a47&e=fd6342eb34) you just issued  and make it point to the training at http://www.praqma.com/training/docker-intro/

But we _urgently_ need to do _something_!

**Comment by monaslarsen** [comment]
Changed image, text and link from DoC to Intro to Docker
