### ISSUE TITLE
List of tags grows too big

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#242]
The list of tags is now exceeding the length of ([some](http://www.praqma.com/stories/praqma-atlassian-partnership/)) posts:

We need to fix this? any ideas how?

![image](https://cloud.githubusercontent.com/assets/155492/13575142/889d0fd6-e487-11e5-96f5-9f067aed3f61.png)

**Comment by illus0r** [comment]
@lakruzz Show 15 first and `▾ Moarrr` button to unhide the rest.

**Comment by lakruzz** [comment]
if it's the top 15 most used ones,

Or we can keep on showing all, but fix the size of the div, and add a scroll-bar?

**Comment by illus0r** [comment]
> Or we can keep on showing all, but fix the size of the div, and add a scroll-bar?

I'd avoid this approach :)
What if we'll strip this list and leave 15 the most useful tags? Links with 1-2 posts inside have no sence :)

**Comment by illus0r** [comment]
On the last week only 3 visitors viewed this page: [google analytics](https://analytics.google.com/analytics/web/?hl=ru&pli=1#report/content-drilldown/a33979353w110395573p115130288/%3F_u.date00%3D20160321%26_u.date01%3D20160327%26explorer-graphOptions.selected%3Danalytics.nthMonth%26explorer-table-tableMode.selected%3Dpie%26explorer-graphMode.mode%3DmotionChart%26explorer-motionChart.xopt%3Danalytics.pageviews%26explorer-motionChart.yopt%3Danalytics.avgPageDuration/)

**Comment by lakruzz** [comment]
@illus0r 

You're looking at was.praqma.com - the true numbers are [here](https://analytics.google.com/analytics/web/?pli=1#report/content-drilldown/a33979353w61397473p62870669/%3F_u.date00%3D20160321%26_u.date01%3D20160327%26explorer-graphOptions.selected%3Danalytics.nthMonth%26explorer-table-tableMode.selected%3Dpie%26explorer-graphMode.mode%3DmotionChart%26explorer-motionChart.xopt%3Danalytics.pageviews%26explorer-motionChart.yopt%3Danalytics.avgPageDuration/)  - approaching 1000 visitors in the week of easter - not bad!

**Comment by illus0r** [comment]
much better :+1:

**Comment by jonnycoull** [comment]
The solution lives here....
https://github.com/Praqma/praqma.com/issues/397

**Comment by lakruzz** [comment]
@illus0r @jonnycoull It seems like this issue is closed for now - isn't it?

![image](https://cloud.githubusercontent.com/assets/155492/20462427/39e1217c-af1e-11e6-9a2d-fb642376d5fe.png)

**Comment by jonnycoull** [comment]
It should be going through milestone close on Monday am.

**Comment by illus0r** [comment]
@jonnycoull I guess this one is to 🔫 it
