### ISSUE TITLE
Front page should show all featured tags

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#243]
...currently it only shows the top three ones:
![image](https://cloud.githubusercontent.com/assets/155492/13575199/d76c2afc-e487-11e5-822e-64738a97d920.png)

vs: http://www.praqma.com/stories/#Featured
![image](https://cloud.githubusercontent.com/assets/155492/13575207/e5296132-e487-11e5-9fb1-2779cfdb6397.png)

**Comment by lakruzz** [comment]
It seems that it's just s threshold that's set in the configuration:
https://github.com/Praqma/praqma.com/blob/gh-pages/index.html

```
{% include posts.html tag="Featured" limit=3 header="News" %}
```

**Comment by illus0r** [comment]
@lakruzz yes! If you'll remove `limit=3`, everything will be shown. Or assing to me :)

**Comment by monaslarsen** [comment]
Removed the limit=3, works fine now
