### ISSUE TITLE
On mobile, newsletter-sign-up and list of tags i shown before content.

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.com#250]
Please change the order, so the article is shown first

**Comment by illus0r** [comment]
@monaslarsen it duplicates subtasks of #124, but faster to implement. Do you want to make it before #124 stuff?

**Comment by monaslarsen** [comment]
You are right, I didn't see 124. 
But if it can be implemented separately, I think you should work on this first - since we always aim for small, well defined issues :)

**Comment by illus0r** [comment]
@monaslarsen хорошо!
