### ISSUE TITLE
Link in "Asessments" is not clickable

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.com#251]
Is there a reason that the link is not made clickable? @lakruzz 
If not, I'll just go ahead and update the file?

<img width="763" alt="screen shot 2016-03-14 at 16 30 43" src="https://cloud.githubusercontent.com/assets/13627068/13749539/3e57d49e-ea02-11e5-8976-0580edff8a62.png">

**Comment by lakruzz** [comment]
@monaslarsen 
no - no reason.

But I think you should point to http://code-maturity.praqma.com/
