### ISSUE TITLE
Add social share options on stories, trainings etc.

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.com#253]
I suggest we add buttons for sharing our divine content on LinkedIn, Facebook etc.
What do you say @lakruzz and @meekrosoft?

**Comment by lakruzz** [comment]
Personally I have seen these buttons ALL OVER the entire internet - I've never pushed a single one of them. When I share something I just copy the url and paste it into G+, Twitetr or LinkedIn.

Have any of you ever used any of these buttons?

**Comment by monaslarsen** [comment]
I'm personally happy with copying the url, but Henrik H said that he was more likely to share content when he saw a button, so I was thinking maybe it was an engineer thing.
I'll be content without, but just wanted to make sure we had touched upon it.
