### ISSUE TITLE
Create story on "Stasi" from blogpost by Henrik

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.com#256]
https://docs.google.com/document/d/13-H2QE0sSf0fQIn2UfaUaz8HGU_9WCLliX43I7ocsbA/edit?ts=56e7e434

**Comment by lakruzz** [comment]
Hi @monaslarsen let me know if you need help on this one - it's approaching urgent

We'd like this story to go live asap, as we have people asking for this specific topic - it would be convenient to point them to this rather than come up with a temporary description.

**Comment by monaslarsen** [comment]
Correct a heading

**Comment by monaslarsen** [comment]
Add a space
