### ISSUE TITLE
Header: make low-fidelity mockups

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#264]
Subtask of #193

![image](https://cloud.githubusercontent.com/assets/797993/14142629/9953c6ca-f68f-11e5-80ce-61817898f966.png)

**Comment by illus0r** [comment]
@lakruzz 
We can contract header's height twice, and even add your contacts there.

![q](https://cloud.githubusercontent.com/assets/797993/14145734/950b1e02-f69d-11e5-849c-4f237bb90bac.png)

On mobile we can show this stuff instead of footer

![dsc_2209](https://cloud.githubusercontent.com/assets/797993/14145642/42574f6e-f69d-11e5-8a4b-81485d45df6d.JPG)

**Comment by illus0r** [comment]
How do you find this idea?

**Comment by lakruzz** [comment]
@illus0r I'm unsure what your are asking - can you elaborate?

**Comment by illus0r** [comment]
@lakruzz oh, sorry
button `Book a free consultation` overlaps the menu on mobile.
I'm presenting the idea of `praqma.com` header, that solves this problem. And BTW reduces header's height and shows your contacts in first place.
What do you think about this approach?

**Comment by illus0r** [comment]
I've showed desktop (more detailed) and mobile (rought) mockups, presenting placement of header's widget.

In fact it's not a header on mobile :) I've moved it to the bottom of the page. It solved the problem, but users have to scroll to the bottom to see the block. If it's a significant drawback, I'll continue elaboration of the problem.

**Comment by illus0r** [comment]
@lakruzz am I using `Action - awaiting feed-back` label properly?

When I need feedback from you I:
- set a `Action - awaiting feed-back` label
- assign task to you

About this task: you've returned it to me, so can I implement [mockups](https://github.com/Praqma/praqma.com/issues/264#issuecomment-203460842)? 🔨  Or you need more detailed mocups first?

**Comment by lakruzz** [comment]
@illus0r Sorry I made a comment too, but maybe I was online, so it never got through?  Anyway the message is: Looks good! go ahead
