### ISSUE TITLE
Mobile ribbon bug

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#266]
![image](https://cloud.githubusercontent.com/assets/797993/14209297/2dc298fc-f82c-11e5-853f-1ff3bc8960b4.png)

**Comment by illus0r** [comment]
There are two options for this
* small fix for current situation
* medium but universal fix

about medium fix:

- [ ] Show words in one line if enough space
- [ ] If <br> is applied or we have not space enough, we break the line
- [ ] If multiple lines, background should be applied to each of them independently

**Comment by illus0r** [comment]
small sollution affects desktop version

![image](https://cloud.githubusercontent.com/assets/797993/14249172/1a9e2b5e-fa81-11e5-8a62-481267c2ce64.png)

![image](https://cloud.githubusercontent.com/assets/797993/14249177/25bede52-fa81-11e5-85f8-987ccd80f74b.png)

**Comment by illus0r** [comment]
@lakruzz which option is better?

**Comment by illus0r** [comment]
sorry, closed instead of #175

**Comment by lakruzz** [comment]
@illus0r Are they comparable? They are different size screen  what am I assessing?

**Comment by illus0r** [comment]
@lakruzz [comment with images](https://github.com/Praqma/praqma.com/issues/266#issuecomment-205293860) shows how the ribbons can look after **small fix**.

**Without this fix** (now) site looks like this (mobile and desktop)

![image](https://cloud.githubusercontent.com/assets/797993/14311467/578ea244-fbf0-11e5-8010-a63283dc10f5.png)


![image](https://cloud.githubusercontent.com/assets/797993/14311490/63a17e08-fbf0-11e5-8039-0035f865d035.png)

**Comment by illus0r** [comment]
I've just breaked the lines to adjust it to small screen

**Comment by illus0r** [comment]
But if I'll spend more time i can come up with more robust and universal solution which doesn't impact on desktop version.
