### ISSUE TITLE
Story tags doesn't work in IE

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#267]
This line produces an error
```
return !$( this ).data("tags").includes(currentTag);
```

![image](https://cloud.githubusercontent.com/assets/797993/14245345/63c53ac4-fa69-11e5-8f06-c0f89a4340f7.png)

**Comment by illus0r** [comment]
@lakruzz I need about an hour to estimate. Should I set `small`?

**Comment by lakruzz** [comment]
@illus0r you need an hour to make an estimate - is that what your saying? Then:

* Create a new issue: "Analyse IE bug"
* Make it reference this issue
* Set labels to:
![image](https://cloud.githubusercontent.com/assets/155492/14685677/c41db4e0-0735-11e6-9b3a-cd5ef8b0eb74.png)

**Comment by illus0r** [comment]
fixed in #277
