### ISSUE TITLE
Dont allow contact form to be empty

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#268]
Only enable button, when all mandatory fields are filled.

Andrey:
>Weird. Perhaps last time it was some search engine indexing bot? Anyhow it would be better to not allow empty forms submissions

**Comment by illus0r** [comment]
Used `required` HTML5 attribute, but it doesn't work in Safari

![image](https://cloud.githubusercontent.com/assets/797993/14282134/b712adba-fb45-11e5-8dbd-164355f1e9a7.png)

**Comment by illus0r** [comment]
Safari is 15% of our audience, so I'll will find some js solution.
