### ISSUE TITLE
Atlassian services on frontpage box

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/praqma.com#272]
I would like a box with "Atlassian Services" on the frontpage - potentially swopping with "come code with up" box.

Ill share the copy with you @monaslarsen

**Comment by adamhenriques** [comment]
@monaslarsen whats the status on this?

**Comment by monaslarsen** [comment]
Not done yet @adamhenriques, but it's in my pipeline

**Comment by monaslarsen** [comment]
We need an Atlassian Services button on the frontpage of www.praqma.com that points to a subpage with content

Content & copy; https://docs.google.com/document/d/1keHQLvjE16Bhsoqp6wqrspOljbRnxtsP5fTYlPdm2lE/edit

**Comment by lakruzz** [comment]
@monaslarsen I don't get the comment above, it seems like the copy in the document you point to is course descriptions, shouldn't it point to training then?

This case need som overall grooming - what's it about? It's marked as small, the documents contains 13 pages - doesn't sound like a small task to produce 13 new sub pages. Maybe discuss (and agree) with @adamhenriques what should happen here.

**Comment by adamhenriques** [comment]
@monalarsen whats status on this? Let me know if you need anything from me
