### ISSUE TITLE
Search bug on stories

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.com#275]
I had this email from Tore at Schlumberger:

On Fri, Apr 15, 2016 at 9:07 AM, Tore Martin Hagen <thagen@slb.com> wrote:
Hi Mike.

I think there is a bug on your web page (and I will assume that it will be fixed and deployed very quickly).

http://www.praqma.com/stories/

Press on any of the links under SEARCH and nothing happens (except from the URL being updated)

http://www.praqma.com/stories/#Git

I am not sure what the intention of this is, but maybe it is that if I press Git it is the same as typing in Git in the search field and press enter?

Tore

**Comment by meekrosoft** [comment]
Hi.

Same behavior on these: 
CentOS 6 with Firefox
Windows with Internet Explorer.

If you don't see the problem then let me know and I will dig out more details for you.

**Comment by illus0r** [comment]
@meekrosoft hmm, possible duplicate of #267?

**Comment by monaslarsen** [comment]
Not sure if you already checked, but Chrome is working just fine for this command.

**Comment by lakruzz** [comment]
@meekrosoft I'm assuming this is a duplicate of #267 which is closed - and therefore the reason why we can not reproduce the behaviour Tore describes
