### ISSUE TITLE
Opinion: image is too dark

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.com#278]
Can we have a brighter image here?
http://www.code-conf.com/code-cph-2016/

**Comment by monaslarsen** [comment]
I can easily brighten the current one - or should we go for another picture all together?

**Comment by lakruzz** [comment]
@meekrosoft and @monaslarsen Should this issue live (then we need to groom it, into an actual task: What should be done) or should it die? (then change prio to 4 - won't have, and close it)
