### ISSUE TITLE
Make clickable links open in new tab

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.com#279]
The links to code-conf.com at http://www.praqma.com/services/code-conf/ open in the same tab, instead of in a new tab. Please change, so people will come back and browse praqma.com when they are done on code-conf.com

**Comment by lakruzz** [comment]
@monaslarsen this is content, something that I'd like you (and @adamhenriques ) should be able to do on your own.

I have assigned this case to you  - instead of @illus0r. Let's meet in a hangout and do it together, it will take 10 mins

**Comment by lakruzz** [comment]
@monaslarsen 

I've closed this one now, have a look at the commit 3723afe to see how it's done
