### ISSUE TITLE
Style tables - SASS

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#306]
Referring to [THE MASS COGNITIVE REVOLUTION DISRUPTING SOFTWARE](http://www.praqma.com/stories/cognitive-revolutions/)

![image](https://cloud.githubusercontent.com/assets/155492/15835146/f11cbe32-2c2e-11e6-9f6e-9580b2cb2302.png)

- [x] Tables are all bold text - only header cells should be bold
- [x] The columns should same-size.

Please style according to the KramDown features of tables:

http://kramdown.gettalong.org/syntax.html#tables

Example - make the following look good (right):

```
|---
| Default aligned | Left aligned | Center aligned | Right aligned
|-|:-|:-:|-:
| First body part | Second cell | Third cell | fourth cell
| Second line |foo | **strong** | baz
| Third line |quux | baz | bar
|---
| Second body
| 2 line
|===
| Footer row
```

Also consider

- [x] vertical align cell content to top

**Comment by lakruzz** [comment]
@illus0r This issue needs to be made ready to work on - but currently needs __an estimate__. I've assigned the case to you, please just do the following:

- Provide a realistic estimate

I assume it's small/medium. if you assess the same, then please give it high priority - start working it immediately 

poke: @timea

**Comment by illus0r** [comment]
@lakruzz hmm, I don't see all the table in bold. Could somebody fix it?

![image](https://cloud.githubusercontent.com/assets/797993/15851534/d91e0896-2ca5-11e6-990e-aa587acfcf83.png)

**Comment by illus0r** [comment]
Current state is 
![image](https://cloud.githubusercontent.com/assets/797993/15856527/a5bb39e2-2cbe-11e6-830b-5a2e4b7daf44.png)

To make heading underlining, separate it with `|---|` or any other acceptable separator

To make table columns have equal width, add `equal` class to this table like this:
```
| Small text | Big text |
|-
| Sma... | Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! Big text! |
{:.equal}
```

It will be rendered to 
![image](https://cloud.githubusercontent.com/assets/797993/15856717/fa3f1460-2cbf-11e6-80d9-c8a3cbd88c71.png)


Unfortunately, kramdown doesn't support `caption` element of table. So captions should be used like
```
From *Sapiens, A Brief History of Humankind (Harari)*, pp 41
{:.table-caption}
```

**Comment by illus0r** [comment]
I've added table formatting information into the README.md
