### ISSUE TITLE
Style tables in stories

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#309]
See tables in : http://www.praqma.com/stories/milestones-and-officehours/ 

The tables use bold text and same size for all content

`<thead>` and `<tbody>` should differ; `<thead>` being more _header_ style - and

**Comment by illus0r** [comment]
@lakruzz 
Houston, we have a problem. It turned out I monitor only code-conf runaway. 
1. Should I monition 3 of them (one per repo)?
2. Should I forget about current milestone until this is fixed?

**Comment by illus0r** [comment]
@lakruzz it seams reprodusable on your computer only. The same story with bold fonts on code-conf.com
That's what I see


![image](https://cloud.githubusercontent.com/assets/797993/16118739/292fe02e-33e1-11e6-8b0b-0c0c77894f7a.png)

**Comment by illus0r** [comment]
Should we close this one? Or at least remove from the runway?

**Comment by lakruzz** [comment]
Problem not reproducible
