### ISSUE TITLE
Introduction to Docker vs CoDe With Containers

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/praqma.com#310]
Are these two training offerings not very similar? If we hold on to both - we need to change the thumbnail of one of them.

http://www.praqma.com/training/code-with-containers/ & http://www.praqma.com/training/docker-intro/

**Comment by monaslarsen** [comment]
GitHub tells me it's made by @meekrosoft a month ago - So Mike, can you enlighten us on why we need two courses so similar? :)

**Comment by monaslarsen** [comment]
Continuous Delivery with containers : One day for technical
