### ISSUE TITLE
Write up story for code academy TRD

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.com#321]
Write up a blog post for code academy in Trondheim

**Comment by meekrosoft** [comment]
Guys,
 @monaslarsen @lakruzz 
Could you eyeball this for me?
https://github.com/Praqma/praqma.com/tree/321-Write-up-story-for-code-academy-TRD

Thanks

**Comment by lakruzz** [comment]
Closed with 2e0095c8ef4cdcd0ce2d1baebc45e08d5f520f79
