### ISSUE TITLE
Update about us page

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/praqma.com#322]
CONTINUOUS DELIVERY TO EVERYBODY

During the first 7 years of our existence, we have helped a large number of companies in- and outside of Denmark implement Continuous Delivery — even before anyone started using the term. We consider ourselves Continuous Delivery Toolsmiths and help our customers with inspiration, strategic consulting, practical implementation and support.

**Proposed updates**
- Update number of years. Is it 9 already?
-  in- and outside of Denmark => in- and outside of Scandinavia

**Comment by lakruzz** [comment]
http://www.praqma.com/about/
