### ISSUE TITLE
Implement protrait tiles

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#342]
Implement the lay-out described in #339 
Feel free to break it up in  more individual issues if necessary.

**Comment by lakruzz** [comment]
@illus0r 
This issue needs to be made ready to work on - but currently needs __an estimate__. I've assigned the case to you, please just do the following:

- Provide a realistic estimate
- Remove the "Action: Needs grooming" label
- Unassign yourself from the issue (just leave the issue unassigned)

poke: @timea

**Comment by illus0r** [comment]
@lakruzz 
We had a slack chat with Jonathan. He showed me these pictures and I've asked:

> illus0r [11:17 PM]  
> Hi, jc! Good evening! Looks doable :slightly_smiling_face:
> So that's a page with team members
> But it's not the only page in `about` section. It'll share the room with `clients`, `jobs`, `offices`, `partners`. So it should share the menu, that gives access to sibling pages
> 
> ![image](https://cloud.githubusercontent.com/assets/797993/17021155/abd9890c-4f4e-11e6-8292-d1c698df8914.png)
> 
> How we can integrate it?
> 
> jc [4:34 PM]  
> Hmm, will have to make a staff icon and sub menu like you suggest?
> 
> illus0r [4:36 PM]  
> this menu can be redesigned. but it should stay on left
> 
> [4:37]  
> if we'll go without redesigning, yep, you're right
> 
> [4:38]  
> one more item should be appended to the left menu
> 
> jc [7:19 PM]  
> Sounds like a plan!
> 

So question is open: how will we implement the sidebar navigation?

**Comment by illus0r** [comment]
I cant assign it to @jonnycoull for some reason.

**Comment by jonnycoull** [comment]
So needs a new icon correct? for this halfway design, before we revamp PRAQMA. @illus0r

**Comment by illus0r** [comment]
@jonnycoull 

So as I got you suggest mockup of that kind:

![image](https://cloud.githubusercontent.com/assets/797993/17022942/7f5bfcba-4f59-11e6-8017-049166fc8004.png)

What do you mean by "revamp PRAQMA"?

**Comment by jonnycoull** [comment]
Yep, just needs a STAFF icon. ah well its on the cards after CODE-CONF. @illus0r

**Comment by illus0r** [comment]
@jonnycoull as for me, every icon can be redrawn, they are awful :) But not obligatory

**Comment by illus0r** [comment]
@jonnycoull 
as I got, if I click not first person (i.e. the last one) it will disappear on its place and will unroll in the top-left corner. Other items will be pushed away to free space. I'll also scroll to top, because the height of the team list may exceed the viewport height. Right?

**Comment by jonnycoull** [comment]
Yes so they jiggle around the main image. I think that would work best but
probably worth a test first

**Comment by jonnycoull** [comment]
@illus0r this is done now right? (re icons)

**Comment by illus0r** [comment]
@jonnycoull 

Icons are changed 
![image](https://cloud.githubusercontent.com/assets/797993/18477328/f85d2d40-79d5-11e6-849d-1755ab196126.png)

**Comment by illus0r** [comment]
@jonnycoull 
I've closed that task.
I made it by the way in https://github.com/Praqma/praqma.com/commit/1337256e3f6c816ddeb3e414114c63c284ada9d7 and forgot to close

**Comment by illus0r** [comment]
Ahh, that's a bug in the workflow. I've bumped it already
This commit closes `#gh pages` task instead of this one :-D
