### ISSUE TITLE
Write a few sample biographies for review

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#343]
@monaslarsen please come up with a few styles for how to present employees.

You presented the [form](https://docs.google.com/a/praqma.net/forms/d/e/1FAIpQLSc_C9iOaEeR-e_-KTLfDCOSfIqGeDZyK-Ut6A2Yw5ysZjFDJQ/viewform?c=0&w=1) every employee should fill out, but personally I'm not fund of this approach; favorite-movie-whats-you-hobby-do-you-own-a-pet kind of bios.

Could you experiment with a few more approaches as well, so we get something to choose from?

I could imagine something that is much more focus on what is this employees strengths and interests in relation to Continuous delivery, DevOps and Praqma. Imagine that the target groups of these bios are our potential customers.

E.g.

>Imagine I setup a meeting with a potential customers, I tell them that I will come myself, and I'll bring Jan as well. Imagine that the customer is curious on who Jan is, they are probably most curious about his professional profile, his role in Praqma his experiences - they might even want to study some of his past experiences on LinkedIn.

**Comment by lakruzz** [comment]
@monaslarsen 

This issue needs to be made ready to work on - but currently needs __an estimate__. I've assigned the case to you, please just do the following:

- Provide a realistic estimate
- Remove the "Action: Needs grooming" label

**Comment by illus0r** [comment]
Added texts and images to site
