### ISSUE TITLE
Make icon for ROUGES GALLERY

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#349]
Subtask of #342 
Now it duplicates another one.

![image](https://cloud.githubusercontent.com/assets/797993/17175722/cdea3600-5411-11e6-8638-630dfbf4f495.png)

**Comment by jonnycoull** [comment]
![new icons](https://cloud.githubusercontent.com/assets/17589853/17669196/9afe2682-6304-11e6-93ac-08cf795a6232.jpg)
![praqma clients](https://cloud.githubusercontent.com/assets/17589853/17669198/9d176244-6304-11e6-8620-30f2f614f39f.png)
![praqma jobs](https://cloud.githubusercontent.com/assets/17589853/17669197/9d174f70-6304-11e6-80e8-e71d1bfb3085.png)
![praqma office](https://cloud.githubusercontent.com/assets/17589853/17669199/9d3502ae-6304-11e6-901d-3001a49b9a71.png)
![praqma partners](https://cloud.githubusercontent.com/assets/17589853/17669200/9d3522b6-6304-11e6-8dc8-7ffe14156c75.jpg)
![praqma staff](https://cloud.githubusercontent.com/assets/17589853/17669201/9d3ee59e-6304-11e6-9825-5b62b10fdc68.png)

**Comment by jonnycoull** [comment]
Hi @illus0r @timea ill upload the into the image directory. see the main mock for which icon goes where.

**Comment by illus0r** [comment]
@jonnycoull to look good on retina they should be at least 300x300. Or other option is to use SVG's
Can you send something of that?

**Comment by jonnycoull** [comment]
@illus0r ill sort that.

**Comment by jonnycoull** [comment]
@illus0r uploaded to images.

**Comment by illus0r** [comment]
Great, found'em in the /images/ folder
