### ISSUE TITLE
Write short text for the ROUGES GALLERY in the menu

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#350]
Subtask of #342

![](https://cloud.githubusercontent.com/assets/797993/17175722/cdea3600-5411-11e6-8638-630dfbf4f495.png)

**Comment by illus0r** [comment]
@monaslarsen, you are fast :)

**Comment by timea** [comment]
What a cooperation 👯

**Comment by monaslarsen** [comment]
I know 💃 
Can we make sure to spell it rogues, though?

**Comment by monaslarsen** [comment]
The text should be:

Meet the clever CoDe brokers and seasoned software agents that make Praqma great
