### ISSUE TITLE
Text covers portrait

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#354]
![image](https://cloud.githubusercontent.com/assets/155492/17291278/3814c67e-57e3-11e6-9d1e-b96972148b8b.png)

We need to fix this problem, that the portrait is cut off in expanded mode. 

- Should the background be transparent?
- Should the portraits all have some "void" space to the left to make room for this?

...Any suggestions?

@jonnycoull @illus0r

**Comment by jonnycoull** [comment]
Can I ask why is this being inplimented without the proper photography?

Which in turn would solve the problem. As the square is a crop, when
selected it shows/reveals a bigger image. Not just the same shot.

**Comment by lakruzz** [comment]
All right, makes sense:

@illus0r let's implement the mock up with portraits that are representative for what it should look like in the end - then!

If you're in doubt, get some samples from @jonnycoull

**Comment by illus0r** [comment]
Hey, @jonnycoull 
I need a sample photo for that.
As I got, you want it to be 3x4 in expanded state and 1x1 for preview. Photo should be aligned by top edge in both sizes.

![image](https://cloud.githubusercontent.com/assets/797993/17294557/54500098-5800-11e6-9ba4-8685bf1aff04.png)

**Comment by jonnycoull** [comment]
Hi mate, do you have an ideal pixel size for each?

**Comment by illus0r** [comment]
@jonnycoull 
now they are 2x3, 356x534px. But we can make them to be 400x600 for easy counting.
(I've mistaken with 3x4)
