### ISSUE TITLE
"praqma.com" does not work - only "www.praqma.com"

### ISSUE THREAD

**Issue by bicschneider** [Praqma/praqma.com#357]
hostname configuration in DNS should all go to www.praqma.com

URL 	`http://praqma.com'
Parent URL	http://localhost:4000/sponsor/, line 192, col 9 (HTML) (CSS)
Real URL	http://praqma.com
Check time	0.479 seconds
Result	Error: error: [Errno 104] Connection reset by peer

**Comment by lakruzz** [comment]
It's the redirect service on gratisdns that's not working, right now, actually their entire site id done right now - I expect it to be fixed soon.

**Comment by lakruzz** [comment]
I have sent a mail to support@gratisdns.dk let's see what their respond is.
