### ISSUE TITLE
Split runway in two.

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/praqma.com#363]
The runway here is used both to track blocking issues and architectural changes.
Those two do not fit good together; one is "all hands on deck", the other a slow moving target.
Suggesting to make a new milestone: Architecture and assign #359 and #297 to it.

**Comment by lakruzz** [comment]
The runway shouldn't be split.

Issues that needs immidiately attention goes to "content update" if it's related to content and "The runway" if it's technical implementation.

Architectural changes will have to enter a planned milestone. They shouldn't reach the runway - the runway and the content update are only for _unplanned_ acute issues

**Comment by lakruzz** [comment]
@sofusalbertsen
