### ISSUE TITLE
Use Bok's icon set on the site

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#367]
Subtask of #342

Use this https://github.com/Praqma/praqma.com/issues/349

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/18390191/d7fb46b2-76b1-11e6-927b-2f8182ebcf06.png)

![image](https://cloud.githubusercontent.com/assets/797993/18390209/e32007b2-76b1-11e6-95af-1618f86f3059.png)

**Comment by jonnycoull** [comment]
is that live now @illus0r

**Comment by illus0r** [comment]
Yep, [check it out yourself](http://www.praqma.com/about/)
One sections is unpublished by now

**Comment by illus0r** [comment]
closed in https://github.com/Praqma/praqma.com/commit/1337256e3f6c816ddeb3e414114c63c284ada9d7
