### ISSUE TITLE
Change 1hour url

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#384]
The 1-hour-free consultation is displayed like this:

![image](https://cloud.githubusercontent.com/assets/155492/18818099/46452478-8371-11e6-93c9-8f4843a8aa55.png)

But the url itself is still referring to 1hour:
![image](https://cloud.githubusercontent.com/assets/155492/18818104/72951038-8371-11e6-944d-7eb2bf2fe216.png)

This was mentioned in [#/marcom/97](https://github.com/Praqma/marcom/issues/97) but moved to here, since an implementation belongs to this repository

**Comment by illus0r** [comment]
Didn't get from description, how to rename it.
@lakruzz can I change the url to `consultation`?

**Comment by illus0r** [comment]
@jonnycoull I'll pick this one `consultation`, if no objections. It can be fixed later
