### ISSUE TITLE
Colour tidy up

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/praqma.com#390]
Fix the existing colour ways on site to match brand parameters. This was issued to you @illus0r @timea a while back, but never actioned when individual pages were built. Each location has a colour. and it needs to be right. Otherwise it is not aligning with Brand colours at the event its self. 

[CODECONF_COLOURS.pdf](https://github.com/Praqma/praqma.com/files/502388/CODECONF_COLOURS.pdf)

**Comment by adamhenriques** [comment]
@jonnycoull  Color updated on http://www.code-conf.com/code-sthlm-2016/. @timea @illus0r will you tidy up throughout; event thumbnail on http://www.code-conf.com/ etc.

**Comment by jonnycoull** [comment]
Thanks @adamhenriques now @illus0r or @timea you need to match the page to this image. Also I've added white icons to the image library, There may be ones there already but just incase. I'm doing so now. 

CHANGES...

CO- to orange. 

BLACK ICONS TO WHITE.

SIB HEADS TO ORANGE. (not on mock but needs doing) 

![screen shot 2016-09-30 at 10 01 14](https://cloud.githubusercontent.com/assets/17589853/18986534/21a70028-86f5-11e6-8598-6610947ebd69.png)

**Comment by illus0r** [comment]
@jonnycoull 
> SIB HEADS TO ORANGE

What's SIB?

**Comment by illus0r** [comment]
- [ ] CO- to orange.
- [ ] BLACK ICONS TO WHITE.
- [ ] SIB HEADS TO ORANGE. (not on mock but needs doing)

**Comment by jonnycoull** [comment]
Sorry supposed to say SUB headings as in (EMBEDDED EDITION AND EXTRAS)

**Comment by adamhenriques** [comment]
@Andrey9kin

**Comment by jonnycoull** [comment]
@illus0r @adamhenriques putting this in the CODE-CONF repository. and closing here.
