### ISSUE TITLE
Long-copy version of the Bonnie Situation needs a review

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#394]
@meekrosoft @BrucePhable 

I distilled (#393)  the content of the Bonnie Situation story from [my own blog](http://www. story.com/en/wolfware-republished/) into a one-piece-long-copy version on [our own website](http://www.praqma.com/stories/the-bonnie-situation/).

me: _"A review would be nice"_
you: _"Come again?"_
me: _"I said a review would be nice"_
you: _"Listen Buster, we're not here to do reviews..."_
me: _"well, I just take pleasure in watching you work"_
you: ...

Hell - this is probably stretching it too far :-)

**Comment by lakruzz** [comment]
I did a few updates myself in #395, be sure to pull latest.

**Comment by Andrey9kin** [comment]
@lakruzz you probably meant Vincent here

Mostly as a habit, Jules is holding a gun in his hand. Suddenly the gun goes off and now Marvin’s brain is all over the ‘74 Chevy Nova.

**Comment by BrucePhable** [comment]
Updated after a bit of copyediting:

https://docs.google.com/document/d/1MVQrW6tpPyoyVs4seNfbBGwgarRJCJbcXt4kGram_Yo/edit?usp=sharing
