### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/praqma.com#396]
Link for our customer cases includes a space resulting in a 404 if copying the link;

http://www.praqma.com/stories/#Customer case

<img width="737" alt="screen shot 2016-10-10 at 16 07 33" src="https://cloud.githubusercontent.com/assets/8004259/19238861/b54267b2-8f03-11e6-8b2e-132cf4094ce5.png">

**Comment by lakruzz** [comment]
Although the url "http://www.praqma.com/stories/#Customer case" is valid in some browsers it's only because these browsers are are implicitly replacing the whitespace with `%20`

@illus0r you should explicitly replace space (`" "`) with "%20" when generation URL from tags.
