### ISSUE TITLE
Don't we have a feed anymore?

### ISSUE THREAD

**Issue by buep** [Praqma/praqma.com#398]
Earlier it was http://www.praqma.com/feed and now again I miss a way to follow new stories.

**Comment by aliprq** [comment]
There seem to be an error on the page.

@illusor can you see if it's something with our content or the module we're
using?

**Comment by illus0r** [comment]
@buep @aliprq thanks for mentioning, I'll have a closer look. I'm assigning myself

**Comment by lakruzz** [comment]
@illus0r what's the status on this one?

I just ran a bisect on the issue, the result was:

```
a66bca8e1c08656024e44376c13e1902b3b9bd48 is the first bad commit
commit a66bca8e1c08656024e44376c13e1902b3b9bd48
Author: Adam Henriques <ah@praqma.com>
Date:   Wed Jun 29 18:33:20 2016 +0200

    close #326 add seminar blogp

```

In short - look at a66bca8e1c08656024e44376c13e1902b3b9bd48

**Comment by lakruzz** [comment]
OK that was easy - closing this one with #438
