### ISSUE TITLE
Bruce's review on bonnie

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#404]
@BrucePhable left this for me https://docs.google.com/document/d/1MVQrW6tpPyoyVs4seNfbBGwgarRJCJbcXt4kGram_Yo/edit?ts=57ff8ae6#heading=h.mmea6r6dxpn

**Comment by lakruzz** [comment]
Hi @BrucePhable 

Thanks for the effort.

It's a little bit tricky to take your notes from the google document, because the copy is already published in  a different format [here in this repository](https://raw.githubusercontent.com/Praqma/praqma.com/gh-pages/_posts/2016-10-08-the-bonnie-situation.md]

So at the end of the day, your improved copy will have to go here too.

__We have two challenges:__

* Mixing content with lay-out
* Being able to see what was actually changed.

The original markdown is actually meant to minimize the first problem to an almost inferior level. However, it requires that one is familiar with MarkDown - I realize that.

Taking the copy it to a google doc, obviously makes it easier to implement the second purpose. The problem is that once the copy is done, it needs to go back into the MarkDown file.

Currently that a relatively manual process. Sentence by sentence.

For future purpose I suggest one of two approaches (They both imply delivering copy as MarkDown).

### GoogleDoc
Copy the raw content of the MarkDown file into a Google Document. and use the "suggesting" mode when editing:

![image](https://cloud.githubusercontent.com/assets/155492/19512141/bea16842-95ea-11e6-8b08-79a006871755.png)

### Commit the MarkDown to GitHub
This means editing the content directly in the existing MarkDown file (using and editor like ATOM) and then committing it to GitHub - either on a separate branch for further joint collaboration, or directly for immediate publishing.

I'm well aware that the second option might seem like gibberish to you at this point. My intention is that I will

- Provide the full tool stack that you need on your Mac to do this (It's [in the making](https://github.com/Praqma/praqma.com/blob/400-The-MarCom-machine-blog-post/_posts/2016-10-18-the-marcom-machine.md) - just not done yet)
- Teach you enough MarkDown + Git/GitHub to make you fall absolutely in love with this approach

...but I realize we're not there yet.

So for now, I believe that we should use the GoogleDoc approach instead. As I said It implies that you edit in MarkDown, but that is so goddamn easy, that it's not even an issue.

@meekrosoft and @jonnycoull I'm poking you on this one too - as It might be relevant for you too.

**Comment by meekrosoft** [comment]
@lakruzz @BrucePhable 
Folks, maybe this is a great example of a situation where the github native user interface can help.  It supports branch creation, review (pull requests), markdown preview, version history.  All through the web ui, so there are no special tools or skills to pick up.  Could we give it a try?

**Comment by lakruzz** [comment]
@meekrosoft  closed #394 which is almost a duplicte for this one - I think we're good for now
