### ISSUE TITLE
What are users subscribing to?

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#42]
A spin off from case #29 

@illus0r:
 
> I'd like to go futher: now a site visitor can only guess what he is subscribing for. I believe, a slight text change can improve conversion. So, could you clarify: why this subscription is useful for a visitor?

**Comment by monaslarsen** [comment]
I agree @illus0r.

How about something like this @lakruzz?

"Subscribe to our Continuous Delivery Newsletter and be in the know on all things CoDe"

"Sign up for our CoDe newsletter: News, techtalk, and the best events in your region"

**Comment by lakruzz** [comment]
Fixed in anoter issue

![image](https://cloud.githubusercontent.com/assets/155492/15590550/acb35880-2398-11e6-936f-13cbb94a33bf.png)
