### ISSUE TITLE
Please publish my blog post "Trust in docker images"

### ISSUE THREAD

**Issue by buep** [Praqma/praqma.com#423]
@drBosse did a technical review, and gave thumbs up on my message makes sense. Also fixed some wording and typos.

I need a real wording/english review please.

Take and use the current version of my blog post, which can be found on my branch for my issue: https://github.com/Praqma/praqma-RnD/blob/1-docker-image-trust/docker/trust-in-docker-images.md

Note the images for the post is in the images folder: https://github.com/Praqma/praqma-RnD/tree/1-docker-image-trust/docker

Comments and changes from Bo can be found here - PR merged and closes, changes are in the current one above: https://github.com/Praqma/praqma-RnD/pull/3

When published, branch and blogpost and images should be replaced by a link to the public post in our RnD repo. 
(Alternative assign back to me, then I do it)

**Comment by buep** [comment]
@monaslarsen - ignore your mail... I created this issue instead. Have a good vacation.

**Comment by lakruzz** [comment]
@buep @monaslarsen 

It would be practical to move the markdown to the praqma/praqma.com repo and put it in the `_posts` folder and include a `published:false` in the front matter.

This way we can build it using `jekyll serve --unpublished` and see how it adapts to the layout on www.praqma.com.

Also we have a pipeline set up in this repo, that will help discover broken links, unused images etc.

Let me know when it's in this repo, and I can give it a review from a lay-out/final touch perspective.

**Comment by buep** [comment]
Will do... assigning myself.

**Comment by buep** [comment]
couldn't get the jekyll to work, would expect to use a container, my local install can't run it.

So be aware I haven't check layout... but added frontmatter as good as I could.
And images and text.

> Also we have a pipeline set up in this repo, that will help discover broken links, unused images etc.

does it run on branches?

**Comment by buep** [comment]
@lakruzz  a few tips would be nice so I can finish more of it

**Comment by lakruzz** [comment]
https://github.com/Praqma/docker-gh-pages
https://hub.docker.com/r/praqma/gh-pages/

**Comment by lakruzz** [comment]
@buep the docker-gh-pages is base on GitHub's github-pages gem, whice they guarantee is in sync with the jekyll version and configuration that is live at github pages.

@MadsNielsen created the image - but the readme file in the repo should be sufficient to get up and running.

**Comment by lakruzz** [comment]
> does it run on branches?

Nope - it runs as part of the integration - (`ready/**` branches)

**Comment by buep** [comment]
I have made some more layout, all I could figure from looking at other post that was non-standard markdown...

Now I need some help with the last parts:

* image for the post in the list and overview
* layout
* short review on wording - Bo and I have done it, maybe someone would like to tip in?

@lakruzz @adamhenriques - help needed for the rest.

**Comment by adamhenriques** [comment]
@buep, i have udloaded blogpost. Please review

**Comment by buep** [comment]
Thanks @adamhenriques - only thing is the container image that is 9MB and loads really slow... I will fix that in another issue.
