### ISSUE TITLE
Fix search bar

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#436]
I fixed #414 and #372 with this commit 0835c2c

I might have ruined something else though - I've looked at a few stories that uses tables - but can's see that anything is looking weird or wrong.

 @illus0r please give it a review.

**Comment by illus0r** [comment]
@lakruzz 
Bug has gone, but others appeared
![image](https://cloud.githubusercontent.com/assets/797993/19863030/affd0d2e-9fa3-11e6-8721-afef3abfd97e.png) (chrome)
![image](https://cloud.githubusercontent.com/assets/797993/19863060/ce4bc8b0-9fa3-11e6-83dc-40c81197d8bd.png) (safari)

**Comment by lakruzz** [comment]
OK, plese fix it

**Comment by illus0r** [comment]
@jonnycoull can you assign the milestone?

**Comment by jonnycoull** [comment]
Gah my mobile has forgotten the git password, can u assign to this weeks
milestone if time, if not then next weeks please. As I'm not near my
computer today

**Comment by illus0r** [comment]
@jonnycoull assigned to week 44

**Comment by illus0r** [comment]
@jonnycoull 
Ahhh, google's code mess. I didn't manage to make things nicely and had to remove placeholder completely.
