### ISSUE TITLE
Blog post on CoDe Alliance

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#437]
We need to tell the story _why_ and _how_ Josra becomes CoDe Alliance

Poke: @buep

**Comment by lakruzz** [comment]
@jonnycoull made a logo suggestion in #430 - he will upload an updated attempt on this one (since #430 is closed)

**Comment by lakruzz** [comment]
A quick hack, to use as placeholder ![code-alliance-3x4](https://cloud.githubusercontent.com/assets/155492/19834997/31abc978-9e78-11e6-85a8-1d3d280510e2.png)

**Comment by lakruzz** [comment]
@buep and @meekrosoft 

I'm done with a first draft. I have committed it and delivered it to `gh-pages` already. 

It's not published though.

Please leave this issue closed and continue with your reviews on #439

**Comment by jonnycoull** [comment]
![codealliance](https://cloud.githubusercontent.com/assets/17589853/19856097/e988c102-9f6f-11e6-8eb0-2a5957a59d7b.jpg)
![codealliance](https://cloud.githubusercontent.com/assets/17589853/19856098/e9898056-9f6f-11e6-92ab-8dad89b3f04f.png)

**Comment by jonnycoull** [comment]
@lakruzz new logo uploaded.
