### ISSUE TITLE
Review CoDe Alliance blog post

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#439]
Follow up on #437: 

review 27ebc2f

The MarkDown is this one: https://github.com/Praqma/praqma.com/blob/gh-pages/_posts/2016-10-30-code-alliance.md

Please, make it easy on ourselves, just make your updates and deliver it directly. (Or leave you comment in the review 27ebc2f)

Leave the `published:false` in then front matter for now though, until we actually have an entry on www.code-conf.com to link to
## How I intend to use this story

I'll send it to all existing and potential members and encourage them to read it and get back to me with feedback

Later I'll actually _call_ each single one of them and discuss the content and encourage them to join in Bjerringbro.

If you think that we need anything to support this purpose, or we need to take something out - then let that be your contribution

**Comment by buep** [comment]
@lakruzz I found some typos and one factual wrong thing - I'm editing the stuff... and adding on this issue as soon as I'm done.

**Comment by buep** [comment]
I pushed my review changes on a branch. 

I'm missing two things in our communication, but it could just be in our mail to the old members maybe. In a few words it something around our motivation and the undergoing changes to come:

* nothing changed, it is still the same just a new name - the renaming will go on for some while adjusting website and taking down old josra website
* it all about our collaboration together your customers as us, and that seems to have been the earlier motivation more than the open source projects... so it is more like a collaboration club going forward and we removed the membership fee to help them easier collaborate...

All the things we talked about internally - I think that is good to know for the members, but maybe shouldn't be part of the blogpost....

**Comment by lakruzz** [comment]
Thanks @buep.

I like your message to the existing messages, but also agree that it belongs to the notification mail, and not in the blog post. I'll add it when the mail goes out.

@meekrosoft, @sofusalbertsen does any of you wanna chip in?

**Comment by sofusalbertsen** [comment]
I've only given it a brief read-through.
Do we want them to chip in with topics for the next gathering, or are we doing the investigation ourselves? If they should chip in as well, then we need to tell them.

**Comment by meekrosoft** [comment]
I have @BrucePhable here this week - I will get him to go through an polish.  I also have some thoughts along the lines of @buep - we need to emphasize that the purpose is to foster collaboration and cross-pollination of experience

**Comment by lakruzz** [comment]
Released in #465
