### ISSUE TITLE
Trust in docker images - edits are missing, why are the blog copied in?

### ISSUE THREAD

**Issue by buep** [Praqma/praqma.com#448]
I can see that the current live blog published now isn't taking from the source where Bo and I have made edits. Thus important edits are missing.

The blog post was edited as part of #423, but @adamhenriques published the blogpost as part of #442 and #444 or #446 - can't really figure it out. 

@lakruzz  @adamhenriques why do you create new issues and not the use #423 for the blog post where all edits actually also lived? Now I can't really figure out where Adam took the text from.... there is not tracebility.

**Comment by buep** [comment]
I'm going to see if I can fix it and figure out what was going on.

**Comment by adamhenriques** [comment]
Thats on me, thought I took it the right place. The reason it was published
as #442 <https://github.com/Praqma/praqma.com/issues/442> and #444
<https://github.com/Praqma/praqma.com/issues/444> is that Jenkins server
was down and had to do a workaround (help from claus)

If you let me know where the right tet is, ill update it.

[image: ____________________________________________________________]
Adam Henriques
Sales & Marketing
ah@praqma.net
+45 28 12 90 94 <+45%2028%2012%2090%2094>
Skype: adamhenriques
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/code-sthlm-2016/>

**Comment by buep** [comment]
Okay @adamhenriques sorry for the harsh comment... didn't know there was a work-around. 

I will go over the blog post now and see if all the edit Bo and I is there. The real problems I guess is not the work-around, the challenge is I don't know what was done or how.

**Comment by adamhenriques** [comment]
@buep, I just copied the text from
https://github.com/Praqma/praqma-RnD/blob/1-docker-image-trust/docker/trust-in-docker-images.md
-
havent edited in the source.

Let me know which is the right source and ill have it updated.



[image: ____________________________________________________________]
Adam Henriques
Sales & Marketing
ah@praqma.net
+45 28 12 90 94 <+45%2028%2012%2090%2094>
Skype: adamhenriques
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/code-sthlm-2016/>

**Comment by buep** [comment]
Okay thanks... the real one lives in a branch matching the blog post #423 issue... but now I know what was going on.

I'll fix it as soon as my meetings are done...

**Comment by buep** [comment]
Talked to Adam... I know all I need now to fix it... but the branch on #423 is deleted in repo, and I have it locally so it is easier for me to fix it

**Comment by lakruzz** [comment]
@buep @adamhenriques @bicschneider 

Sorry, this limbo situation is not really covered in the phlow yet - I've made an issue on it 
praqma/the-phlow#9
