### ISSUE TITLE
Related posts: style

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#454]
![image](https://cloud.githubusercontent.com/assets/797993/20007333/c9bc5416-a2ac-11e6-8d28-d64381f957ad.png)

![image](https://cloud.githubusercontent.com/assets/797993/20007362/f69041c8-a2ac-11e6-879f-8777261d9f89.png)

Subtask of #397

- [ ] Show up to 6 related posts
- [ ] Show up to 2 on laptop
- [ ] Show show not more than 2 tags on plaques

We WON'T show related posts in the content.

**Comment by illus0r** [comment]
@jonnycoull 
almost done

some notes:

- it turned out, some images are of different heights. Someone needs to align them to some constant ratio. Should I wait with pushing until this is done? Or it can be fixed with styles, I guess. Should work in most cases. But it needs some extra time.
- script gets two post with bigger about of matching tags. If current post has no matching tags with any others, no *related posts* will be shown. Sometimes only one is shown.
- I show up to 2 _related posts_ on any devices. I can explain, why I did so :)

Let me know, what should we do to close it?

![image](https://cloud.githubusercontent.com/assets/797993/20140091/5b0a6dae-a69a-11e6-8260-b58ad98387d2.png)

**Comment by jonnycoull** [comment]
@illus0r  Can you build a rule that the orange box sits on the image so many pixels from the top so they all match? also is there a way so that the headlines are always 2 decks, so the orange boxes are also the same size.

**Comment by illus0r** [comment]
@jonnycoull hi there!
As for me the only way to what you want is
- [ ] set constant height to orange box
- [ ] show no more than 2 rows of title. Hide the rest
- [ ] fit the image the nicest way (so it covers the box above the orange one)

What did I misunderstand?

**Comment by illus0r** [comment]
so every box will be of the same height

**Comment by illus0r** [comment]
@jonnycoull 

I've delivered, [take a look](http://localhost:3006/stories/code-academy/).

1. Made long titles to fade away
1. short titles occupy two lines as well to keep orange boxes aligned.

![image](https://cloud.githubusercontent.com/assets/797993/20184786/fa52e4f0-a77a-11e6-9c61-001b47924eed.png)
![image](https://cloud.githubusercontent.com/assets/797993/20184839/19a316fe-a77b-11e6-9398-5f7f57f39b16.png)

**Comment by jonnycoull** [comment]
@illus0r the user needs to be able to read the whole headline, lets reduce the size of that type. find the current longest headline and make it fit. then work backwards from that.  then we'll imply a rule to writers that no headline too be over this character length.

**Comment by illus0r** [comment]
@jonnycoull All right than. But why not to fix the long titles? It's the Lars way, I believe)

**Comment by jonnycoull** [comment]
@illus0r there will on occasion be long titles so we need to make it work for all eventualities. short, med, and long. so crack on and lets see how you can sort it as I instructed. thanks.

**Comment by illus0r** [comment]
@jonnycoull what if we'll step back from the ideal and make additional third line, if title is huge?

**Comment by illus0r** [comment]
In most cases title's heights will match

**Comment by jonnycoull** [comment]
lets see what that looks like.

**Comment by illus0r** [comment]
@jonnycoull 

![image](https://cloud.githubusercontent.com/assets/797993/20220327/248e64e2-a83e-11e6-897a-d1c181e10e4a.png)
![image](https://cloud.githubusercontent.com/assets/797993/20220383/6015783e-a83e-11e6-9c41-05e422eb0cd4.png)

**Comment by illus0r** [comment]
@jonnycoull if there's no more than 2 lines, the height of elements will be equal. Now there's no posts with titles for 3 lines on the site. I've pushed the result

**Comment by illus0r** [comment]
@jonnycoull what should we do to close it?
When we're going to meet?

**Comment by jonnycoull** [comment]
@illus0r good to close.

**Comment by Andrey9kin** [comment]
@illus0r @jonnycoull just saw that you implemented related articles. Nice!
