### ISSUE TITLE
Tags: hide tags into accordion on laptop

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#456]
Subtask of #397

![image](https://cloud.githubusercontent.com/assets/797993/20007520/aac9b872-a2ad-11e6-8936-bc926d2e6312.png)

**Comment by illus0r** [comment]
It turned out the search control were broken before, now it became evident

![image](https://cloud.githubusercontent.com/assets/797993/20425974/23429f2c-ad8e-11e6-9174-56ec8a979a1b.png)

I wanted to fix it but decided to push changes before the scram meeting

**Comment by illus0r** [comment]
The button is blue on production only

![image](https://cloud.githubusercontent.com/assets/797993/20426392/fb7383c4-ad8f-11e6-9a70-805d7fbf72d5.png)

I'll fix it in this issue

**Comment by jonnycoull** [comment]
<img width="312" alt="screen shot 2016-11-18 at 10 23 12" src="https://cloud.githubusercontent.com/assets/17589853/20426891/0ef6e600-ad79-11e6-8553-d86e293978ce.png">

ok, @illus0r can we make sure it all lines up to. thanks.

**Comment by illus0r** [comment]
sure, man

**Comment by illus0r** [comment]
@jonnycoull check it out on prod!

**Comment by jonnycoull** [comment]
Cool! lets close.
