### ISSUE TITLE
Tags: implement mobile mockup

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#457]
Subtask of #397

**Comment by illus0r** [comment]
@jonnycoull
Do we really need it now, as we want to rethink the basics of our tag system?
This issue is about these mockups:

![](https://cloud.githubusercontent.com/assets/797993/19934299/32f356aa-a127-11e6-8b02-38ebc52bc8e0.png)

**Comment by jonnycoull** [comment]
I think to put it in place so it works as it may be some time till they cut
down the list

**Comment by jonnycoull** [comment]
@illus0r add filter name to mobile
