### ISSUE TITLE
Social: add buttons on laptop

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#458]
Subtask of #397

![image](https://cloud.githubusercontent.com/assets/797993/20007602/0f79f5ac-a2ae-11e6-8c07-2c808fbacbdb.png)

**Comment by illus0r** [comment]
Implemented buttons. Solved the problem of adblock which cuts them out. Tried to solve the problem with wrong image on G+ but didn't manage it to work

**Comment by jonnycoull** [comment]
So are we done? @illus0r also did you not see bruce copy? 

And now for something completely different...

**Comment by illus0r** [comment]
@jonnycoull can you post the copy here? I've missed it

**Comment by illus0r** [comment]
@jonnycoull found them in the next task :)

**Comment by jonnycoull** [comment]
And now for something completely different...INSERTLINK

From Praqma.com
