### ISSUE TITLE
Social: add buttons on mobile

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#459]
Subtask of #397
Small if laptop version is implemented. And if whatsapp button will work without a hitch.

![image](https://cloud.githubusercontent.com/assets/797993/20007646/4e95dbac-a2ae-11e6-95bf-495637499302.png)

**Comment by jonnycoull** [comment]
@BrucePhable need a line of copy. ill sort with bruce for example....

Subject.. Check this out...Event manager
link to site.

**Comment by BrucePhable** [comment]
Let's make the line "And now for something completely different..."

**Comment by jonnycoull** [comment]
so use that for fb, twitter, wasp and email. @illus0r 

And now for something completely different..
"paste link to article"

on email subject heading should be the same. then title of the article.

**Comment by illus0r** [comment]
@BrucePhable hi there! I've used your copy for whatsapp and email messages. But for twitter, facebook and google plus I've set just title+url. Will that work?

Test it here http://www.praqma.com/stories/praqtitioner/, i. e.

**Comment by jonnycoull** [comment]
@illus0r yeah thats cool.

**Comment by BrucePhable** [comment]
@illus0r Yes, this is fine.
