### ISSUE TITLE
Post: make images to be big

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#460]
Subtask of #397

![image](https://cloud.githubusercontent.com/assets/797993/20007761/d330d4fc-a2ae-11e6-8209-349175c8fd1a.png)

![image](https://cloud.githubusercontent.com/assets/797993/20007795/f4996aa0-a2ae-11e6-882c-60ad825d540f.png)

**Comment by illus0r** [comment]
We discussed with Bok: first image should always be on top and 100% width.

**Comment by jonnycoull** [comment]
@illus0r who was that to?

**Comment by illus0r** [comment]
The note for myself

**Comment by illus0r** [comment]
@jonnycoull check it out online!

**Comment by illus0r** [comment]
@jonnycoull is it done?

**Comment by jonnycoull** [comment]
Hi @illus0r i think these images are too deep/square. see attached, it cuts of the text in a web window. not ideal. `i think we will have to crop and set an ideal upload dimension for the blogs and send this to mike, lars and every one else that posts that this is the new set size make your images fit this moving forward. so 600x300 pixels. see attached. this will need sorting asap as it looks really ugly. 

<img width="1039" alt="screen shot 2016-11-16 at 09 59 48" src="https://cloud.githubusercontent.com/assets/17589853/20342950/6e8dd542-abe4-11e6-86e2-9eb36c0847b3.png">
![new version](https://cloud.githubusercontent.com/assets/17589853/20342951/6ea7b5de-abe4-11e6-935d-ee9ac0c44c64.jpg)

**Comment by jonnycoull** [comment]
@illus0r how soon can this be fixed?

**Comment by illus0r** [comment]
@jonnycoull so you want me to make a task for content related image cropping?

**Comment by jonnycoull** [comment]
@illus0r yes, then going forward they can be uploaded at the correct size.

**Comment by jonnycoull** [comment]
@illus0r aren't most this shape any way?

**Comment by illus0r** [comment]
@jonnycoull So you want me to fix images aspect ratios to valid proportions (1x2)?

> aren't most this shape any way?
didn't get you

**Comment by jonnycoull** [comment]
originally aren't most images landscape, anyway it needs to be more like the mock which i made 600/300 @illus0r im not sure what that is is scale,

**Comment by illus0r** [comment]
@jonnycoull I still have no idea what do you want me to do. Sorry, man :)

* fix all post's images?
* make a guidelines to prevent this mistake in the future?
* show images in 600/300 even if they are of other proportions?

**Comment by jonnycoull** [comment]
@illus0r the images are too big. they take up the whole open window, you need to see image and headline as above mock up. So yes fix all post images. Ill tell @monaslarsen @adamhenriques @meekrosoft @lakruzz that posts images need tone 600x300 pixels in size or that proportion to work properly as a rule. Show images in 600/300 but do not squash or distort.

**Comment by illus0r** [comment]
@jonnycoull all right then

**Comment by illus0r** [comment]
@jonnycoull some images won't crop nicely

![image](https://cloud.githubusercontent.com/assets/797993/20391366/22f4e8a4-ace4-11e6-8cec-71836ad72522.png)

So I'll try another hack to not to fix images. I'll just show them cropped on the post pages

**Comment by illus0r** [comment]
@jonnycoull

**Comment by illus0r** [comment]
@jonnycoull some images are weird, but they are weird in the only place, not everywhere :) They should be fixed. You can give this work to me or poke someone else.

![image](https://cloud.githubusercontent.com/assets/797993/20391959/d0d3bc82-ace6-11e6-9527-073f61e1ad38.png)

**Comment by jonnycoull** [comment]
@illus0r or myself will send @monaslarsen @adamhenriques @meekrosoft @lakruzz  putting out an email to make sure new posts have a top image that is of the correct proportions 712x356
