### ISSUE TITLE
Trending posts: show them

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#461]
Subtask of #397

![image](https://cloud.githubusercontent.com/assets/797993/20007905/6e1025b8-a2af-11e6-9db1-d6b387ebfa70.png)

**Comment by jonnycoull** [comment]
@illus0r to time box a solution

**Comment by illus0r** [comment]
I'd take 4 hours to investigate jsvascript solution. Script should pull GA data and show most viewed articles

**Comment by jonnycoull** [comment]
@illus0r to investigate this week, discuss solution week 48.

**Comment by illus0r** [comment]
I'll investigate if i'll have some time after others issues are done

**Comment by jonnycoull** [comment]
@illus0r investigating solution for this,

**Comment by jonnycoull** [comment]
@illus0r 4hrs . time box.

**Comment by illus0r** [comment]
@jonnycoull 
it looks doable with [Google Analytics superProxy](https://github.com/googleanalytics/google-analytics-super-proxy#readme), this option was suggested on Jekyll talks [in reply to my post](https://talk.jekyllrb.com/t/list-the-most-viewed-posts-without-plugins/3330). I'm somewhere in the middle [of this manual](https://www.youtube.com/watch?v=Uaap53YrmFU), but there a lot of hitches on my way. First of all I'm new to google apps. The help of expert could speed me up.

Approximate time is about 8 hours to make a Google Analytics superProxy application, which makes a `json` with analytics data (but there's no guarantee, this approach may turn out invalid after all). This `json` will be parsed and used to make a list of relevant posts, that worth a separate `medium` task, because we need to make an analytics data caching in order to speed page loading up.

I didn't look at alternative solution ([OOCharts](http://acrl.ala.org/techconnect/post/two-free-methods-for-sharing-google-analytics-data-visualizations-on-a-public-dashboard)) still it can handle 10000 requests per month, that's too little.

**Comment by illus0r** [comment]
Hey, @jonnycoull! Should I go on?

**Comment by jonnycoull** [comment]
I think most of that is beyond my understanding but if @lakruzz ok's it them im happy to push on. 
It will become more useful to have as we make more changes and social media gets better.

**Comment by jonnycoull** [comment]
@illus0r lets see how actionable this is, start work on it and we'll see by monday.

**Comment by illus0r** [comment]
@lakruzz to solve this issue we should access analytics data somehow. Possible option is to set up the https://github.com/googleanalytics/google-analytics-super-proxy on one of your servers or on Google Apps (payed). Which option is better?

**Comment by lakruzz** [comment]
@illis0r it shall run in the cloud, somehow, setting it up as angoogle apps seems fine, but it shall rune ynder an accout the we control ourselves.

Can you make a brief description of the install and deploy procedure you plan to use (create a seperate issue for eatablishing infrastructure) then I will hook you up with someone her fra Praqma, who can work with you on that.
