### ISSUE TITLE
Related posts: in content

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#462]
Subtask of #397

Show related posts in the content on mobile

![image](https://cloud.githubusercontent.com/assets/797993/20007958/a6c6a9ae-a2af-11e6-952f-16e8df566ac0.png)

**Comment by jonnycoull** [comment]
@illus0r to figure out how to analyse post content. currently at base of mobile page as a temp fix.

**Comment by jonnycoull** [comment]
@illus0r to investigate week 48.

**Comment by jonnycoull** [comment]
@illus0r to change to floating pop up box. rotating between most relevant trending articles

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/20669415/2c92259e-b585-11e6-8cdd-c27633ca3bd5.png)

**Comment by jonnycoull** [comment]
@illus0r to implement new box as discussed.

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/20882359/a20c5508-baf1-11e6-9f31-d42d7f0f8b40.png)

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/20882380/b9078be2-baf1-11e6-8b84-a86dd2e2f03d.png)

**Comment by jonnycoull** [comment]
@illus0r to finish and close today. so we can close milestone.

**Comment by jonnycoull** [comment]
@illus0r ETA? then i think once done have a look at 49 to see whats possible or have a chat if needs be.

**Comment by illus0r** [comment]
@jonnycoull it's live now, but different from a mockup. I had to make font smaller so there were a room for long titles.

**Comment by jonnycoull** [comment]
@illus0r how can i view to close?

**Comment by illus0r** [comment]
@jonnycoull on any article of praqma.com:

![lf2ffkzuje](https://cloud.githubusercontent.com/assets/797993/20922812/89f0d358-bbba-11e6-884f-5bb05c955966.gif)
