### ISSUE TITLE
Mobile navigation redesign

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#463]
Subtask of #397

![](https://cloud.githubusercontent.com/assets/797993/20006842/818bf6bc-a2aa-11e6-8305-30b20dbaff5e.png)

**Comment by illus0r** [comment]
@jonnycoull what to do else?

![image](https://cloud.githubusercontent.com/assets/797993/20307987/0aba0c70-ab53-11e6-8f3c-424865eb1b69.png)

**Comment by illus0r** [comment]
@jonnycoull It's on production now

**Comment by jonnycoull** [comment]
@illus0r cool, good work. ready to close.

**Comment by illus0r** [comment]
@jonnycoull i've closed
