### ISSUE TITLE
Tags: new system

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#464]
Tag list grew big and hard to explore. We need either rethink it's design (i.e. showing most popular tags, attaching a post number to each of them)

Or we need to rethink the whole tag system

**Comment by jonnycoull** [comment]
Could the 5 most popular be visible then an option to see all?

**Comment by illus0r** [comment]
@jonnycoull Did you mean `most filled with articles`? That's easy

**Comment by jonnycoull** [comment]
@illus0r yes, then an option to see all?

**Comment by illus0r** [comment]
@jonnycoull doable as well

**Comment by jonnycoull** [comment]
Speak to @lakruzz to rearrange to categories to reduce amount of tags.

**Comment by lakruzz** [comment]
List only the - say - top 15 tags.

Related to #494

**Comment by jonnycoull** [comment]
Closing this fixing via top 15 to show. #494 and amend that to action @lakruzz
