### ISSUE TITLE
Staff page: make the text block scrollable

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/praqma.com#477]
https://github.com/Praqma/code-conf.com/issues/406

relates to issue in codeconf.

**Comment by jonnycoull** [comment]
@illus0r scroll bar issue.

**Comment by illus0r** [comment]
Content scrolls on expanded items only. The scrollbar will be nice even on windows.

![ihbfsgoibb](https://cloud.githubusercontent.com/assets/797993/20590522/a2b26c24-b234-11e6-9cd7-c2dc9f72f8c1.gif)

**Comment by illus0r** [comment]
@jonnycoull I make `gif`s when the new functionality is invisible on production (it this case the whole page is unpublished)

**Comment by jonnycoull** [comment]
@illus0r good work. were working on bios and faces to names right now.
