### ISSUE TITLE
Redirect to Josra

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#487]
http://www.praqma.com/codeall

should redirect to www.josra.org

...until we get something up there!

**Comment by lakruzz** [comment]
@illus0r can you take care of this one?

**Comment by illus0r** [comment]
@lakruzz sure

**Comment by illus0r** [comment]
@lakruzz I'm going to create a page with suggested url and make a redirect. This page won't appear anywhere on the site navigation.
