### ISSUE TITLE
Show the number of posts near tags on the right column

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#494]
![image](https://cloud.githubusercontent.com/assets/797993/20483573/b81710a2-b003-11e6-9744-7ada8bb806d4.png)

@jonnycoull made this issue after our meeting

**Comment by jonnycoull** [comment]
Cool @illus0r

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/20667338/cd425a60-b579-11e6-9365-741f32d34634.png)
