### ISSUE TITLE
Blog post about VMware API scripting

### ISSUE THREAD

**Issue by martinmosegaard** [Praqma/praqma.com#495]

**Comment by buep** [comment]
Read your post, nothing really to edit though I might have missed a few typos.

I have some general comments:

* you don't mention licenses, isn't it correct that vCenter is licensed, but you used 30 days trial? The same with ESXi, which is still free but as far as I remember "write"-access through API requires a license?

Else conceptually I like you share your thoughts and effort on the matter with the API, but I would expect some more advanced stuff soon? Maybe mention there will be a follow-up on the matter soon, where we explain how it is used say with build systems or testing if that is true?

**Comment by martinmosegaard** [comment]
Thanks for the comments @buep 

I haven't heard of the ESX write-access expiring. But I would have to look into that.

I would prefer not to promise a follow-up, since sometimes that never happens :) But if you think this post is a useful start, I would like to post it and then maybe I will get to writing more advanced stuff later.

**Comment by buep** [comment]
I'm good with publishing it, maybe let @adamhenriques or @praqma-thi do the English wording proof-read - I'm definitely not the best for that.

But I think it is worth getting something out on our blog related to scripting infrastructure. Even though you never get the second part.

**Comment by buep** [comment]
Licensing wise ESXi might have changes, but if you're using evaluations you can't really know yet.

**Comment by martinmosegaard** [comment]
I think you are right that vCenter is 30 days. I think that ESX eval of 60 days is eval of all features, then after that, you only have the free version, but where you can still use the API to work with VMs for example. I am not sure - I have never run the same VM for 60 days.

**Comment by buep** [comment]
https://community.spiceworks.com/topic/260092-what-are-the-limitations-of-free-esxi
http://blogs.vmware.com/vsphere/2009/06/esxi-vs-esx-a-comparison-of-features.html

Especially this: http://www.doublecloud.org/2011/01/free-esxi-and-apicli-support/

**Comment by buep** [comment]
and this https://communities.vmware.com/thread/496649?start=0&tstart=0

**Comment by buep** [comment]
and this http://stackoverflow.com/questions/30055221/enable-management-api-in-vmware-vsphere-hypervisor

**Comment by martinmosegaard** [comment]
Thanks. That is worth mentioning.

**Comment by monaslarsen** [comment]
Assigned to Mona for getting online
