### ISSUE TITLE
2:1 crop on blog posts

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/praqma.com#497]
Change crops on stories. 

<img width="761" alt="screen shot 2016-11-28 at 12 42 25" src="https://cloud.githubusercontent.com/assets/17589853/20668922/43df3230-b569-11e6-9138-cdebfa2e8cf2.png">
<img width="761" alt="screen shot 2016-11-28 at 12 42 25 2" src="https://cloud.githubusercontent.com/assets/17589853/20668934/502ab2c6-b569-11e6-9a3e-2648e74a271c.png">

**Comment by jonnycoull** [comment]
@illus0r only start this once #498 is complete

**Comment by illus0r** [comment]
@jonnycoull I'm supposed to leave current image proportions, scale every new wide image so it's height were the same and left-right sides were cropped. So every image will have the same visual size on the list but not on the post page. Right?

![image](https://cloud.githubusercontent.com/assets/797993/20924104/d082aff2-bbc0-11e6-90a7-f08cdecb646f.png)

**Comment by jonnycoull** [comment]
@illus0r you received the images ok? im not sure cropping will work, id prefer they kept the same proportions as the main blog (wider) , otherwise were just swapping the problem around.

**Comment by illus0r** [comment]
@jonnycoull 
Got your images.
![image](https://cloud.githubusercontent.com/assets/797993/20925613/084ed426-bbc9-11e6-8fb4-0f6a3d458396.png)

**Comment by jonnycoull** [comment]
@illus0r why isn't this finished?

**Comment by jonnycoull** [comment]
@illus0r close today
