### ISSUE TITLE
Go throug all storie images

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#498]
Should now be in 2:1 format, width minimum 800px

**Comment by jonnycoull** [comment]
![alecbaldwin](https://cloud.githubusercontent.com/assets/17589853/20669235/fba273f4-b56a-11e6-878b-6485a1e53bbf.jpg)

**Comment by jonnycoull** [comment]
ok forget that we'll have to do it manually.

**Comment by jonnycoull** [comment]
@lakruzz @illus0r where do these live? so i can edit them?

**Comment by jonnycoull** [comment]
So new size is 800x400. ? @illus0r is that right

**Comment by illus0r** [comment]
@jonnycoull yep, fixed that [in docs ](https://github.com/Praqma/praqma.com/blob/gh-pages/readme.md#avatar)

Do you want me to cut this new format images to make them 4x3 on the post list? Or what to do next in this issue?

![image](https://cloud.githubusercontent.com/assets/797993/20832820/6c74a0c2-b89d-11e6-89f7-498186fc8810.png)

**Comment by jonnycoull** [comment]
I'm fixing the main images to be bigger and 2:1 so once that's complete
(Monday I hope) we can fix these

**Comment by BrucePhable** [comment]
@illus0r , @jonnycoull  has these ready where do u want them? please notify me.

**Comment by jonnycoull** [comment]
@illus0r where should I put these pics??

**Comment by jonnycoull** [comment]
to email @illus0r files to replace.

**Comment by illus0r** [comment]
@jonnycoull that's what you sent to me, right?

**Comment by illus0r** [comment]
@jonnycoull is it a duplicate of https://github.com/Praqma/praqma.com/issues/497?

**Comment by jonnycoull** [comment]
@illus0r this one is the blog post images them selves, #497 refers to making the same ratio image on the stories page.

**Comment by jonnycoull** [comment]
@illus0r why isn't this closed?
