### ISSUE TITLE
Get pictures online

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#500]
@MarieLKruse has already delivered the first batch of portraits, we need to get them online, so we can see them in context.

Lets create an entry for each person we have a picture for, so we don't have to look at the mockup anymore

![image](https://cloud.githubusercontent.com/assets/155492/20703912/d45247bc-b61d-11e6-9283-2cb62c6ac944.png)

**Comment by lakruzz** [comment]
Apparently this seems related to #493

**Comment by lakruzz** [comment]
We can not wait for the Bios, until #492 is done we will have to go with some _Lorem Ipsum ..._ text

**Comment by jonnycoull** [comment]
a repeat of #493 all images are in the images/employees/ @illus0r
