### ISSUE TITLE
Rename _employees collection

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#503]
We need to rename the employees collection to `people` so the URL becomes

`http://www.praqma.com/about/people/`

Rather than 

`http://www.praqma.com/about/employees/`

**Comment by jonnycoull** [comment]
@illus0r can you easily fix this? if so assign size and week 48 if its doable this week.

**Comment by jonnycoull** [comment]
@illus0r rename to people.

**Comment by jonnycoull** [comment]
@illus0r after close of week 48 do this first.

**Comment by illus0r** [comment]
@jonnycoull @lakruzz that's great if collection's name has `s` in the end. That makes it easy to think out an evident name for an element of this collection.

`employees` — `employee`
`people` — `?`

**Comment by jonnycoull** [comment]
@illus0r in this case people (is the plural) singular would be person but people is what lars wants so lets make it so please. People is good.

**Comment by illus0r** [comment]
@jonnycoull on any article of praqma.com:

![lf2ffkzuje](https://cloud.githubusercontent.com/assets/797993/20922812/89f0d358-bbba-11e6-884f-5bb05c955966.gif)

**Comment by illus0r** [comment]
@lakruzz @jonnycoull 
renamed 
`employees` to `people`
`employee` to `people-person`

**Comment by jonnycoull** [comment]
@illus0r I think a little may have got lost in translation. @lakruzz thoughts?

**Comment by lakruzz** [comment]
@illus0r 

>renamed
>  employees to people
>  employee to people-person

You lost me - what are we talking about???

**Comment by illus0r** [comment]
@lakruzz 
I'm talking about changes applied to variable names. What did I make wrong?

**Comment by lakruzz** [comment]
Hmmm OK (?)

but why: `employee to people-person`
why not just `employee to person`

Anyway, if it's a variable name -it think we'll survive :-)

**Comment by illus0r** [comment]
@lakruzz
If i see `event` variable, it's clear enough, that it is an element of `events` array. But it's hard to guess, to which array relates `person` variable. I'd think there should be `persons` array somewhere :-) So my point was to keep relation between names of array and it's element.

**Comment by lakruzz** [comment]
No - _persons_ in a group becomes _people_ 

http://dictionary.cambridge.org/grammar/british-grammar/person-persons-or-people

:-)

**Comment by illus0r** [comment]
@lakruzz :D Good. Can I rename?

**Comment by lakruzz** [comment]
yes please
