### ISSUE TITLE
Enable JC to run the web locally

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#506]
Picking up from the sidetracked dialog in #493

To enable your machine to run Jekyll run this:
https://github.com/Praqma/Marcom-machine

When that is done run the following command in your terminal:

```
cd ~
git clone https://github.com/Praqma/praqma.com.git
cd praqma.com
jekyll serve --unpublished
open http://localhost:4000
```

**Comment by jonnycoull** [comment]
Cool! thanks @lakruzz

**Comment by lakruzz** [comment]
@jonnycoull 
Should we share a hangout - I can guide you ;-)

**Comment by jonnycoull** [comment]
@lakruzz yes please!

**Comment by lakruzz** [comment]
@jonnycoull 
From start (no terminal running) you do:

Start the terminal (<CMD>+<SPACE> -> type "Terminal" -> hit <ENTER>) 

```
cd  ~/github/praqma.com
jekyll serve --unpublished

```

**Comment by jonnycoull** [comment]
Hi @lakruzz ill close this now yes?
