### ISSUE TITLE
Shoot remaining Staff protraits

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.com#510]
We need pictures of the following staff:

- [x] @alexsedova (Alexandra)
- [x] @andrey9kin (Andrey)
- [x] @buep (Bue)
- [x] @hoeghh (Henrik)
- [x] @jkrag (Jan)
- [x] @madsbaggesen (Mads B.)
- [ ] @martinmosegaard (Martin)
- [x] @michaelmadsen (Michael)
- [x] @praqmatim (Tim)
- [x] @randomsort (Johan)
- [x] @smadarmhansen (Smadar)
- [x] @thakangbaby (Sonny)
- [x] @jasminecrozier (Jasmine)

@MarieLKruse will shoot these on Thursday Dec 8th when we're all gathered in CPH

**Comment by JKrag** [comment]
Just want to note that I will unfortunately not be in CPH on Thursday.

**Comment by jonnycoull** [comment]
@MarieLKruse lets have a hangout on weds to go over our shoot list, and available time slots if any when to shoot staff. @lakruzz do you have an agenda i can see or will it be available on the day? thanks.

**Comment by martinmosegaard** [comment]
I will also not be in CPH Thursday. I will be there Friday at 3 PM.

**Comment by praqmaTim** [comment]
When I first saw the mail. I didn't catch the "portrait" part and read it as "Shoot the remaining staff" :laughing: 

Thought maybe I should stay home :smiley:

**Comment by buep** [comment]
Our @praqmaTim you could also make sure not to be in the "remaining" group... ;-)


@lakruzz - how much of me is going to be in the picture? I need to chose a T-shirt ...

**Comment by MarieLKruse** [comment]
Hey Jonathan !
I have time tomorrow until around 2 pm - maybe at 12?

2016-12-05 10:32 GMT+01:00 jonnycoull <notifications@github.com>:

**Comment by jonnycoull** [comment]
12 is cool, I'll set a reminder

**Comment by MarieLKruse** [comment]
cool, speak tomorrow :)


2016-12-06 20:43 GMT+01:00 jonnycoull <notifications@github.com>:

> 12 is cool, I'll set a reminder
>
>

**Comment by jonnycoull** [comment]
Did the invite come through? I'm rubbish at google hangouts!

**Comment by lakruzz** [comment]
http://ringopumpkin.quickconnect.to/photo
