### ISSUE TITLE
Set up a server for accessing GA

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.com#520]
Subissue of #461

**Comment by Sharor** [comment]
I just talked with Lars Kruse, I'll have a look at it :) @illus0r

**Comment by illus0r** [comment]
@Sharor great! Thanks!

**Comment by Sharor** [comment]
@illus0r 
Just a quick update - I went through the github project for the google superproxy you posted in #461 and google cloud seems to allow setting up the whole server as part of their gcloud. 

I spent some time fighting with the google cloud inteface, as it seems like the steps described dont actually work as described. Im currently trying to upload the superproxy, to allow setting up queries :)

**Comment by Sharor** [comment]
![screenshot from 2016-12-13 12-57-27](https://cloud.githubusercontent.com/assets/12966451/21139571/d5a9a8dc-c133-11e6-8b00-c36040a19e55.png)

**Comment by Sharor** [comment]
Is that all you need @illus0r to work with it?

**Comment by illus0r** [comment]
@Sharor wow, incredible! I've stuck right at the beginning of this manual 😀  
My email is zor667@gmail.com, thanks!

**Comment by Sharor** [comment]
You just have to visit  https://praqmatrending-152410.appspot.com/admin/activate and you should be good :) 

The page you interact with is https://praqmatrending-152410.appspot.com/ otherwise. Glad to be of help!

**Comment by jonnycoull** [comment]
@illus0r SO where are we at in terms of getting this sorted? thanks for the assist @Sharor

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/21182159/b67cacae-c212-11e6-865f-8e43e3821b08.png)

@Sharor Error 400 after clicking 
![image](https://cloud.githubusercontent.com/assets/797993/21182172/c527e23c-c212-11e6-97e3-26fcebfd1a3c.png)

**Comment by Sharor** [comment]
Hmm thats weird. I get that too now. Ill have a look at it @illus0r

**Comment by illus0r** [comment]
Thanks, @Sharor! Let me know when to try again.

**Comment by Sharor** [comment]
![screenshot from 2016-12-15 15-35-07](https://cloud.githubusercontent.com/assets/12966451/21227921/2acac856-c2dc-11e6-8545-f0f0ce502908.png)

**Comment by Sharor** [comment]
"Progress"  :+1:

**Comment by Sharor** [comment]
![screenshot from 2016-12-15 15-49-51](https://cloud.githubusercontent.com/assets/12966451/21228466/2ec88360-c2de-11e6-92b9-ec8fe591b9d6.png)
![screenshot from 2016-12-15 15-49-58](https://cloud.githubusercontent.com/assets/12966451/21228467/2fe98c44-c2de-11e6-8316-b450edd120b4.png)

**Comment by Sharor** [comment]
I think it works!

**Comment by Sharor** [comment]
Confirmed to work for @illus0r also, closing issue ! :+1:
