### ISSUE TITLE
All shot staff pics inserted in Gallery MVP

### ISSUE THREAD

**Issue by jonnycoull** [Praqma/praqma.com#528]
Insert all images supplied into MVP.

**Comment by jonnycoull** [comment]
@illus0r whats the status of this? I've had no response.

**Comment by illus0r** [comment]
@jonnycoull Currently I work on https://github.com/Praqma/praqma.com/issues/524, I'll do this one in the evening, is it ok?

**Comment by jonnycoull** [comment]
@illus0r coolio.

**Comment by illus0r** [comment]
@jonnycoull 
![image](https://cloud.githubusercontent.com/assets/797993/21198512/bfe26cd2-c250-11e6-8786-e6ff255de8d0.png)
